//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowScriptEngineSlimDX.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlowScriptEngineSlimDX.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   加算します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Add_Summary {
            get {
                return ResourceManager.GetString("Add_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   加算した数値です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Add_Value {
            get {
                return ResourceManager.GetString("Add_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アルファ値を設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Color4_FromElement_Alpha {
            get {
                return ResourceManager.GetString("Color4_FromElement_Alpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   B値を設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Color4_FromElement_Blue {
            get {
                return ResourceManager.GetString("Color4_FromElement_Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   G値を設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Color4_FromElement_Green {
            get {
                return ResourceManager.GetString("Color4_FromElement_Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   R値を設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Color4_FromElement_Red {
            get {
                return ResourceManager.GetString("Color4_FromElement_Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   要素を指定して色を生成します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Color4_FromElement_Summary {
            get {
                return ResourceManager.GetString("Color4_FromElement_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   色を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Color4_FromElement_Value {
            get {
                return ResourceManager.GetString("Color4_FromElement_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   色を表します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Color4_Summary {
            get {
                return ResourceManager.GetString("Color4_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   色のアルファ値を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Color4_Value_Alpha {
            get {
                return ResourceManager.GetString("Color4_Value_Alpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   色のB値を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Color4_Value_Blue {
            get {
                return ResourceManager.GetString("Color4_Value_Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   色のG値を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Color4_Value_Green {
            get {
                return ResourceManager.GetString("Color4_Value_Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   色のR値を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Color4_Value_Red {
            get {
                return ResourceManager.GetString("Color4_Value_Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   色を取得、設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Color4_Value_Summary {
            get {
                return ResourceManager.GetString("Color4_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   割算します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Devide_Summary {
            get {
                return ResourceManager.GetString("Devide_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   割算した数値です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Devide_Value {
            get {
                return ResourceManager.GetString("Devide_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   等しいかどうかを調べます に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Equal_Summary {
            get {
                return ResourceManager.GetString("Equal_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   等しいかどうかです に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Equal_Value {
            get {
                return ResourceManager.GetString("Equal_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   一つ目の引数です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FirstArgument {
            get {
                return ResourceManager.GetString("FirstArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   回転量を設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_AffineTransformation_Rotation_Summary {
            get {
                return ResourceManager.GetString("Matrix_AffineTransformation_Rotation_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   回転の中心を設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_AffineTransformation_RotationCenter_Summary {
            get {
                return ResourceManager.GetString("Matrix_AffineTransformation_RotationCenter_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   拡大率を設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_AffineTransformation_Scale_Summary {
            get {
                return ResourceManager.GetString("Matrix_AffineTransformation_Scale_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   3次元のアフィン変換マトリックスを生成します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_AffineTransformation_Summary {
            get {
                return ResourceManager.GetString("Matrix_AffineTransformation_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   移動量を設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_AffineTransformation_Translation_Summary {
            get {
                return ResourceManager.GetString("Matrix_AffineTransformation_Translation_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変換行列を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_AffineTransformation_Value_Summary {
            get {
                return ResourceManager.GetString("Matrix_AffineTransformation_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   回転量を設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_AffineTransformation2D_Rotation_Summary {
            get {
                return ResourceManager.GetString("Matrix_AffineTransformation2D_Rotation_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   回転の中心を設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_AffineTransformation2D_RotationCenter_Summary {
            get {
                return ResourceManager.GetString("Matrix_AffineTransformation2D_RotationCenter_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   拡大率を設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_AffineTransformation2D_Scale_Summary {
            get {
                return ResourceManager.GetString("Matrix_AffineTransformation2D_Scale_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2次元のアフィン変換マトリックスを生成します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_AffineTransformation2D_Summary {
            get {
                return ResourceManager.GetString("Matrix_AffineTransformation2D_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   移動量を設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_AffineTransformation2D_Translation_Summary {
            get {
                return ResourceManager.GetString("Matrix_AffineTransformation2D_Translation_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変換行列を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_AffineTransformation2D_Value_Summary {
            get {
                return ResourceManager.GetString("Matrix_AffineTransformation2D_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象の行列を設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_Determinant_Matrix_Summary {
            get {
                return ResourceManager.GetString("Matrix_Determinant_Matrix_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   行列の行列式を計算します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_Determinant_Summary {
            get {
                return ResourceManager.GetString("Matrix_Determinant_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   行列式を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_Determinant_Value_Summary {
            get {
                return ResourceManager.GetString("Matrix_Determinant_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象の行列を設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_GetColumn_A_Summary {
            get {
                return ResourceManager.GetString("Matrix_GetColumn_A_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象の列インデックスを設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_GetColumn_Index_Summary {
            get {
                return ResourceManager.GetString("Matrix_GetColumn_Index_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   行列の列ベクトルを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_GetColumn_Summary {
            get {
                return ResourceManager.GetString("Matrix_GetColumn_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   列ベクトルを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_GetColumn_Value_Summary {
            get {
                return ResourceManager.GetString("Matrix_GetColumn_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象の行列を設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_GetRow_A_Summary {
            get {
                return ResourceManager.GetString("Matrix_GetRow_A_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象の行インデックスを設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_GetRow_Index_Summary {
            get {
                return ResourceManager.GetString("Matrix_GetRow_Index_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   行列の行ベクトルを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_GetRow_Summary {
            get {
                return ResourceManager.GetString("Matrix_GetRow_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   行ベクトルを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_GetRow_Value_Summary {
            get {
                return ResourceManager.GetString("Matrix_GetRow_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   単位行列を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_Identity_Summary {
            get {
                return ResourceManager.GetString("Matrix_Identity_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   単位行列を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_Identity_Value_Summary {
            get {
                return ResourceManager.GetString("Matrix_Identity_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   回転量を設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_RotationAxis_Angle_Summary {
            get {
                return ResourceManager.GetString("Matrix_RotationAxis_Angle_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   軸を設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_RotationAxis_Axis_Summary {
            get {
                return ResourceManager.GetString("Matrix_RotationAxis_Axis_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   軸の周りの回転行列を計算します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_RotationAxis_Summary {
            get {
                return ResourceManager.GetString("Matrix_RotationAxis_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変換行列を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_RotationAxis_Value_Summary {
            get {
                return ResourceManager.GetString("Matrix_RotationAxis_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象のクォータニオンを設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_RotationQuaternion_Quaternion_Summary {
            get {
                return ResourceManager.GetString("Matrix_RotationQuaternion_Quaternion_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クォータニオンによる回転行列を計算します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_RotationQuaternion_Summary {
            get {
                return ResourceManager.GetString("Matrix_RotationQuaternion_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変換行列を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_RotationQuaternion_Value_Summary {
            get {
                return ResourceManager.GetString("Matrix_RotationQuaternion_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   回転量を設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_RotationX_Angle_Summary {
            get {
                return ResourceManager.GetString("Matrix_RotationX_Angle_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   X軸での回転行列を計算します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_RotationX_Summary {
            get {
                return ResourceManager.GetString("Matrix_RotationX_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変換行列を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_RotationX_Value_Summary {
            get {
                return ResourceManager.GetString("Matrix_RotationX_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   回転量を設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_RotationY_Angle_Summary {
            get {
                return ResourceManager.GetString("Matrix_RotationY_Angle_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Y軸での回転行列を計算します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_RotationY_Summary {
            get {
                return ResourceManager.GetString("Matrix_RotationY_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変換行列を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_RotationY_Value_Summary {
            get {
                return ResourceManager.GetString("Matrix_RotationY_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   回転量を設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_RotationZ_Angle_Summary {
            get {
                return ResourceManager.GetString("Matrix_RotationZ_Angle_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Z軸での回転行列を計算します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_RotationZ_Summary {
            get {
                return ResourceManager.GetString("Matrix_RotationZ_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変換行列を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_RotationZ_Value_Summary {
            get {
                return ResourceManager.GetString("Matrix_RotationZ_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   拡大率を設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_Scaling_Scale_Summary {
            get {
                return ResourceManager.GetString("Matrix_Scaling_Scale_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   拡大行列を計算します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_Scaling_Summary {
            get {
                return ResourceManager.GetString("Matrix_Scaling_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変換行列を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_Scaling_Value_Summary {
            get {
                return ResourceManager.GetString("Matrix_Scaling_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   回転量を設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_Transformation_Rotation_Summary {
            get {
                return ResourceManager.GetString("Matrix_Transformation_Rotation_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   回転の中心を設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_Transformation_RotationCenter_Summary {
            get {
                return ResourceManager.GetString("Matrix_Transformation_RotationCenter_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   拡大率を設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_Transformation_Scaling_Summary {
            get {
                return ResourceManager.GetString("Matrix_Transformation_Scaling_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   拡大の中心位置を設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_Transformation_ScalingCenter_Summary {
            get {
                return ResourceManager.GetString("Matrix_Transformation_ScalingCenter_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   拡大回転を設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_Transformation_ScalingRotation_Summary {
            get {
                return ResourceManager.GetString("Matrix_Transformation_ScalingRotation_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ３次元変換行列を計算します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_Transformation_Summary {
            get {
                return ResourceManager.GetString("Matrix_Transformation_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   移動量を設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_Transformation_Translation_Summary {
            get {
                return ResourceManager.GetString("Matrix_Transformation_Translation_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変換行列を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_Transformation_Value_Summary {
            get {
                return ResourceManager.GetString("Matrix_Transformation_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   回転量を設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_Transformation2D_Rotation_Summary {
            get {
                return ResourceManager.GetString("Matrix_Transformation2D_Rotation_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   回転の中心を設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_Transformation2D_RotationCenter_Summary {
            get {
                return ResourceManager.GetString("Matrix_Transformation2D_RotationCenter_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   拡大率を設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_Transformation2D_Scaling_Summary {
            get {
                return ResourceManager.GetString("Matrix_Transformation2D_Scaling_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   拡大の中心位置を設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_Transformation2D_ScalingCenter_Summary {
            get {
                return ResourceManager.GetString("Matrix_Transformation2D_ScalingCenter_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   拡大回転を設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_Transformation2D_ScalingRotation_Summary {
            get {
                return ResourceManager.GetString("Matrix_Transformation2D_ScalingRotation_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ２次元変換行列を計算します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_Transformation2D_Summary {
            get {
                return ResourceManager.GetString("Matrix_Transformation2D_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   移動量を設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_Transformation2D_Translation_Summary {
            get {
                return ResourceManager.GetString("Matrix_Transformation2D_Translation_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変換行列を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_Transformation2D_Value_Summary {
            get {
                return ResourceManager.GetString("Matrix_Transformation2D_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   移動行列を計算します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_Translation_Summary {
            get {
                return ResourceManager.GetString("Matrix_Translation_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   移動量を設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_Translation_Translation_Summary {
            get {
                return ResourceManager.GetString("Matrix_Translation_Translation_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変換行列を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_Translation_Value_Summary {
            get {
                return ResourceManager.GetString("Matrix_Translation_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象の行列を設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_Transpose_Matrix_Summary {
            get {
                return ResourceManager.GetString("Matrix_Transpose_Matrix_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   転置行列を計算します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_Transpose_Summary {
            get {
                return ResourceManager.GetString("Matrix_Transpose_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   転置行列を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_Transpose_Value_Summary {
            get {
                return ResourceManager.GetString("Matrix_Transpose_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   M11要素の値を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_Value_M11_Summary {
            get {
                return ResourceManager.GetString("Matrix_Value_M11_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   M12要素の値を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_Value_M12_Summary {
            get {
                return ResourceManager.GetString("Matrix_Value_M12_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   M13要素の値を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_Value_M13_Summary {
            get {
                return ResourceManager.GetString("Matrix_Value_M13_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   M14要素の値を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_Value_M14_Summary {
            get {
                return ResourceManager.GetString("Matrix_Value_M14_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   M21要素の値を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_Value_M21_Summary {
            get {
                return ResourceManager.GetString("Matrix_Value_M21_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   M22要素の値を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_Value_M22_Summary {
            get {
                return ResourceManager.GetString("Matrix_Value_M22_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   M23要素の値を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_Value_M23_Summary {
            get {
                return ResourceManager.GetString("Matrix_Value_M23_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   M24要素の値を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_Value_M24_Summary {
            get {
                return ResourceManager.GetString("Matrix_Value_M24_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   M31要素の値を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_Value_M31_Summary {
            get {
                return ResourceManager.GetString("Matrix_Value_M31_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   M32要素の値を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_Value_M32_Summary {
            get {
                return ResourceManager.GetString("Matrix_Value_M32_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   M33要素の値を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_Value_M33_Summary {
            get {
                return ResourceManager.GetString("Matrix_Value_M33_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   M34要素の値を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_Value_M34_Summary {
            get {
                return ResourceManager.GetString("Matrix_Value_M34_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   M41要素の値を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_Value_M41_Summary {
            get {
                return ResourceManager.GetString("Matrix_Value_M41_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   M42要素の値を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_Value_M42_Summary {
            get {
                return ResourceManager.GetString("Matrix_Value_M42_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   M43要素の値を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_Value_M43_Summary {
            get {
                return ResourceManager.GetString("Matrix_Value_M43_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   M44要素の値を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_Value_M44_Summary {
            get {
                return ResourceManager.GetString("Matrix_Value_M44_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   行列を分解します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_Value_Summary {
            get {
                return ResourceManager.GetString("Matrix_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象の行列を取得、設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Matrix_Value_Value_Summary {
            get {
                return ResourceManager.GetString("Matrix_Value_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   乗算します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Multiply_Summary {
            get {
                return ResourceManager.GetString("Multiply_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   乗算した結果です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Multiply_Value {
            get {
                return ResourceManager.GetString("Multiply_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象のクォータニオンを設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Quaternion_Angle_Quaternion_Summary {
            get {
                return ResourceManager.GetString("Quaternion_Angle_Quaternion_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クォータニオンの角度を計算します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Quaternion_Angle_Summary {
            get {
                return ResourceManager.GetString("Quaternion_Angle_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クォータニオンの角度を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Quaternion_Angle_Value_Summary {
            get {
                return ResourceManager.GetString("Quaternion_Angle_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象のクォータニオンを設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Quaternion_Axis_Quaternion_Summary {
            get {
                return ResourceManager.GetString("Quaternion_Axis_Quaternion_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クォータニオンの軸を計算します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Quaternion_Axis_Summary {
            get {
                return ResourceManager.GetString("Quaternion_Axis_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クォータニオンの軸を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Quaternion_Axis_Value_Summary {
            get {
                return ResourceManager.GetString("Quaternion_Axis_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   一つ目のクォータニオンを設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Quaternion_Dot_A_Summary {
            get {
                return ResourceManager.GetString("Quaternion_Dot_A_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   二つ目のクォータニオンを設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Quaternion_Dot_B_Summary {
            get {
                return ResourceManager.GetString("Quaternion_Dot_B_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   二つのクォータニオンの内積を計算します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Quaternion_Dot_Summary {
            get {
                return ResourceManager.GetString("Quaternion_Dot_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クォータニオンの内積を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Quaternion_Dot_Value_Summary {
            get {
                return ResourceManager.GetString("Quaternion_Dot_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象のクォータニオンを設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Quaternion_Exponential_Quaternion_Summary {
            get {
                return ResourceManager.GetString("Quaternion_Exponential_Quaternion_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クォータニオンの指数を計算します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Quaternion_Exponential_Summary {
            get {
                return ResourceManager.GetString("Quaternion_Exponential_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クォータニオンの指数を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Quaternion_Exponential_Value_Summary {
            get {
                return ResourceManager.GetString("Quaternion_Exponential_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象のクォータニオンです に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Quaternion_Length_Quaternion_Summary {
            get {
                return ResourceManager.GetString("Quaternion_Length_Quaternion_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クォータニオンの長さを計算します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Quaternion_Length_Summary {
            get {
                return ResourceManager.GetString("Quaternion_Length_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クォータニオンの長さを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Quaternion_Length_Value_Summary {
            get {
                return ResourceManager.GetString("Quaternion_Length_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象のクォータニオンです に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Quaternion_LengthSquared_Quaternion_Summary {
            get {
                return ResourceManager.GetString("Quaternion_LengthSquared_Quaternion_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クォータニオンの長さの２乗を計算します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Quaternion_LengthSquared_Summary {
            get {
                return ResourceManager.GetString("Quaternion_LengthSquared_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クォータニオンの長さの２乗を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Quaternion_LengthSquared_Value_Summary {
            get {
                return ResourceManager.GetString("Quaternion_LengthSquared_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象のクォータニオンを設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Quaternion_Logarithm_Quaternion_Summary {
            get {
                return ResourceManager.GetString("Quaternion_Logarithm_Quaternion_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クォータニオンのログを計算します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Quaternion_Logarithm_Summary {
            get {
                return ResourceManager.GetString("Quaternion_Logarithm_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クォータニオンのログを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Quaternion_Logarithm_Value_Summary {
            get {
                return ResourceManager.GetString("Quaternion_Logarithm_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象のクォータニオンです に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Quaternion_Normalize_Quaternion_Summary {
            get {
                return ResourceManager.GetString("Quaternion_Normalize_Quaternion_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正規化したクォータニオンを計算します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Quaternion_Normalize_Summary {
            get {
                return ResourceManager.GetString("Quaternion_Normalize_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正規化したクォータニオンを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Quaternion_Normalize_Value_Summary {
            get {
                return ResourceManager.GetString("Quaternion_Normalize_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   角度を設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Quaternion_RotationAxis_Angle_Summary {
            get {
                return ResourceManager.GetString("Quaternion_RotationAxis_Angle_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   軸を設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Quaternion_RotationAxis_Axis_Summary {
            get {
                return ResourceManager.GetString("Quaternion_RotationAxis_Axis_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定した軸周りの回転したクォータニオンを計算します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Quaternion_RotationAxis_Summary {
            get {
                return ResourceManager.GetString("Quaternion_RotationAxis_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   回転したクォータニオンを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Quaternion_RotationAxis_Value_Summary {
            get {
                return ResourceManager.GetString("Quaternion_RotationAxis_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   回転行列を設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Quaternion_RotationMatrix_Matrix_Summary {
            get {
                return ResourceManager.GetString("Quaternion_RotationMatrix_Matrix_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   回転行列からクォータニオンを計算します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Quaternion_RotationMatrix_Summary {
            get {
                return ResourceManager.GetString("Quaternion_RotationMatrix_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クォータニオンを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Quaternion_RotationMatrix_Value_Summary {
            get {
                return ResourceManager.GetString("Quaternion_RotationMatrix_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クォータニオンを分解します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Quaternion_Value_Summary {
            get {
                return ResourceManager.GetString("Quaternion_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象のクォータニオンを取得、設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Quaternion_Value_Value_Summary {
            get {
                return ResourceManager.GetString("Quaternion_Value_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クォータニオンのW成分を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Quaternion_Value_W_Summary {
            get {
                return ResourceManager.GetString("Quaternion_Value_W_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クォータニオンのX成分を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Quaternion_Value_X_Summary {
            get {
                return ResourceManager.GetString("Quaternion_Value_X_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クォータニオンのY成分を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Quaternion_Value_Y_Summary {
            get {
                return ResourceManager.GetString("Quaternion_Value_Y_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クォータニオンのZ成分を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Quaternion_Value_Z_Summary {
            get {
                return ResourceManager.GetString("Quaternion_Value_Z_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   二つ目の引数です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SecondArgument {
            get {
                return ResourceManager.GetString("SecondArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   減算します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Substract_Summary {
            get {
                return ResourceManager.GetString("Substract_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   減算した結果です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Substract_Value {
            get {
                return ResourceManager.GetString("Substract_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ターゲットのタイプを調べます に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TemplateIsType_Summary {
            get {
                return ResourceManager.GetString("TemplateIsType_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ターゲットです に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TemplateIsType_Target {
            get {
                return ResourceManager.GetString("TemplateIsType_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ターゲットがタイプであったかどうかです に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TemplateIsType_Value {
            get {
                return ResourceManager.GetString("TemplateIsType_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最大のベクトルを設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_Clamp_Max_Summary {
            get {
                return ResourceManager.GetString("Vector_Clamp_Max_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最小のベクトルを設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_Clamp_Min_Summary {
            get {
                return ResourceManager.GetString("Vector_Clamp_Min_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ベクトルを最大、最小以内に制限します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_Clamp_Summary {
            get {
                return ResourceManager.GetString("Vector_Clamp_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   制限されたベクトルを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_Clamp_Value_Summary {
            get {
                return ResourceManager.GetString("Vector_Clamp_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象のベクトルを設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_Clamp_Vector_Summary {
            get {
                return ResourceManager.GetString("Vector_Clamp_Vector_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   二つのベクトルから外積を計算します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_Cross_Summary {
            get {
                return ResourceManager.GetString("Vector_Cross_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ベクトルの外積を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_Cross_Value_Summary {
            get {
                return ResourceManager.GetString("Vector_Cross_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   二つのベクトルの距離を計算します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_Distance_Summary {
            get {
                return ResourceManager.GetString("Vector_Distance_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ベクトルの距離を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_Distance_Value_Summary {
            get {
                return ResourceManager.GetString("Vector_Distance_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   二つのベクトルの距離の2乗を計算します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_DistanceSquared_Summary {
            get {
                return ResourceManager.GetString("Vector_DistanceSquared_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ベクトルの距離の2乗を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_DistanceSquared_Value_Summary {
            get {
                return ResourceManager.GetString("Vector_DistanceSquared_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ベクトルの内積を計算します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_Dot_Summary {
            get {
                return ResourceManager.GetString("Vector_Dot_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ベクトルの内積を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_Dot_Value_Summary {
            get {
                return ResourceManager.GetString("Vector_Dot_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   要素を指定してベクトルを生成します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_FromElement_Summary {
            get {
                return ResourceManager.GetString("Vector_FromElement_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ベクトルを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_FromElement_Value_Summary {
            get {
                return ResourceManager.GetString("Vector_FromElement_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   W成分を設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_FromElement_W_Summary {
            get {
                return ResourceManager.GetString("Vector_FromElement_W_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   X成分を設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_FromElement_X_Summary {
            get {
                return ResourceManager.GetString("Vector_FromElement_X_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Y成分を設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_FromElement_Y_Summary {
            get {
                return ResourceManager.GetString("Vector_FromElement_Y_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Z成分を設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_FromElement_Z_Summary {
            get {
                return ResourceManager.GetString("Vector_FromElement_Z_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ベクトルの長さを計算します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_Length_Summary {
            get {
                return ResourceManager.GetString("Vector_Length_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ベクトルの長さを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_Length_Value_Summary {
            get {
                return ResourceManager.GetString("Vector_Length_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象のベクトルを設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_Length_Vector_Summary {
            get {
                return ResourceManager.GetString("Vector_Length_Vector_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ベクトルの長さの2乗を計算します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_LengthSquared_Summary {
            get {
                return ResourceManager.GetString("Vector_LengthSquared_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ベクトルの長さの2乗を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_LengthSquared_Value_Summary {
            get {
                return ResourceManager.GetString("Vector_LengthSquared_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象のベクトルを設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_LengthSquared_Vector_Summary {
            get {
                return ResourceManager.GetString("Vector_LengthSquared_Vector_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   二つのベクトルの最大の要素からなるベクトルを計算します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_Max_Summary {
            get {
                return ResourceManager.GetString("Vector_Max_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最大の要素を持つベクトルを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_Max_Value_Summary {
            get {
                return ResourceManager.GetString("Vector_Max_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   二つのベクトルの最小の要素からなるベクトルを計算します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_Min_Summary {
            get {
                return ResourceManager.GetString("Vector_Min_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最小の要素を持つベクトルを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_Min_Value_Summary {
            get {
                return ResourceManager.GetString("Vector_Min_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   成分をそれぞれ掛け合わせたベクトルを計算します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_Modulate_Summary {
            get {
                return ResourceManager.GetString("Vector_Modulate_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   成分を掛け合わせたベクトルを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_Modulate_Value_Summary {
            get {
                return ResourceManager.GetString("Vector_Modulate_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正規化したベクトルを計算します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_Normalize_Summary {
            get {
                return ResourceManager.GetString("Vector_Normalize_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正規化したベクトルを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_Normalize_Value_Summary {
            get {
                return ResourceManager.GetString("Vector_Normalize_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象のベクトルを設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_Normalize_Vector_Summary {
            get {
                return ResourceManager.GetString("Vector_Normalize_Vector_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象のベクトルを設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_Transform_A_Summary {
            get {
                return ResourceManager.GetString("Vector_Transform_A_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象の行列を設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_Transform_B_Summary {
            get {
                return ResourceManager.GetString("Vector_Transform_B_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ベクトルを行列で変形します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_Transform_Summary {
            get {
                return ResourceManager.GetString("Vector_Transform_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変形されたベクトルを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_Transform_Value_Summary {
            get {
                return ResourceManager.GetString("Vector_Transform_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ベクトルを設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_TransformCoordinate_A_Summary {
            get {
                return ResourceManager.GetString("Vector_TransformCoordinate_A_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   行列を設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_TransformCoordinate_B_Summary {
            get {
                return ResourceManager.GetString("Vector_TransformCoordinate_B_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ベクトルを指定の行列で変形しW=1に投影します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_TransformCoordinate_Summary {
            get {
                return ResourceManager.GetString("Vector_TransformCoordinate_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変形したベクトルを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_TransformCoordinate_Value_Summary {
            get {
                return ResourceManager.GetString("Vector_TransformCoordinate_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   法線ベクトルを設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_TransformNormal_A_Summary {
            get {
                return ResourceManager.GetString("Vector_TransformNormal_A_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   行列を設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_TransformNormal_B_Summary {
            get {
                return ResourceManager.GetString("Vector_TransformNormal_B_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   法線ベクトルを指定の行列で変形します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_TransformNormal_Summary {
            get {
                return ResourceManager.GetString("Vector_TransformNormal_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変形したベクトルを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_TransformNormal_Value_Summary {
            get {
                return ResourceManager.GetString("Vector_TransformNormal_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   W方向の単位ベクトルを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_UnitW_Summary {
            get {
                return ResourceManager.GetString("Vector_UnitW_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   単位ベクトルを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_UnitW_Value_Summary {
            get {
                return ResourceManager.GetString("Vector_UnitW_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   X方向の単位ベクトルを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_UnitX_Summary {
            get {
                return ResourceManager.GetString("Vector_UnitX_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   単位ベクトルを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_UnitX_Value_Summary {
            get {
                return ResourceManager.GetString("Vector_UnitX_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Y方向の単位ベクトルを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_UnitY_Summary {
            get {
                return ResourceManager.GetString("Vector_UnitY_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   単位ベクトルを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_UnitY_Value_Summary {
            get {
                return ResourceManager.GetString("Vector_UnitY_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Z方向の単位ベクトルを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_UnitZ_Summary {
            get {
                return ResourceManager.GetString("Vector_UnitZ_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   単位ベクトルを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_UnitZ_Value_Summary {
            get {
                return ResourceManager.GetString("Vector_UnitZ_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ベクトルを分解します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_Value_Summary {
            get {
                return ResourceManager.GetString("Vector_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   W成分を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_Value_W_Summary {
            get {
                return ResourceManager.GetString("Vector_Value_W_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   X成分を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_Value_X_Summary {
            get {
                return ResourceManager.GetString("Vector_Value_X_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Y成分を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_Value_Y_Summary {
            get {
                return ResourceManager.GetString("Vector_Value_Y_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Z成分を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_Value_Z_Summary {
            get {
                return ResourceManager.GetString("Vector_Value_Z_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ゼロベクトルを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_Zero_Summary {
            get {
                return ResourceManager.GetString("Vector_Zero_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ゼロベクトルを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector_Zero_Value_Summary {
            get {
                return ResourceManager.GetString("Vector_Zero_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   文字列の場合は X:0 Y:0のようなフォーマットで可能です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector2_Value_Value_Summary {
            get {
                return ResourceManager.GetString("Vector2_Value_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   文字列の場合は X:0 Y:0 Z:0のようなフォーマットで可能です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector3_Value_Value_Summary {
            get {
                return ResourceManager.GetString("Vector3_Value_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   文字列の場合は X:0 Y:0 Z:0 W:0のようなフォーマットで可能です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vector4_Value_Value_Summary {
            get {
                return ResourceManager.GetString("Vector4_Value_Value_Summary", resourceCulture);
            }
        }
    }
}
