//--------------------------------------------------------
// This code is generated by AutoFastGenerator.
// You should not modify the code.
//--------------------------------------------------------

namespace FlowScriptEngineBasic.FlowSourceObjects.Pair
{
    public partial class FromKeyValueFlowSourceObject
    {
        public override object GetPropertyValue(string propertyName)
        {
            switch (propertyName)
            {
                case "Pair":
                    return Pair;
                default:
                    return null;
            }
        }

        protected override void SetPropertyValue(string propertyName, object value)
        {
            switch (propertyName)
            {
                case "Key":
                    Key = (System.Object)value;
                    break;
                case "Value":
                    Value = (System.Object)value;
                    break;
            }
        }

    }
}
