//--------------------------------------------------------
// This code is generated by AutoFastGenerator.
// You should not modify the code.
//--------------------------------------------------------

namespace FlowScriptEnginePPD.FlowSourceObjects.Graphics
{
    public partial class GameInterfaceFlowSourceObject
    {
        public override object GetPropertyValue(string propertyName)
        {
            switch (propertyName)
            {
                case "ComboLayer":
                    return ComboLayer;
                case "ConnectLayer":
                    return ConnectLayer;
                case "HoldLayer":
                    return HoldLayer;
                case "MarkEffectLayer":
                    return MarkEffectLayer;
                case "MarkLayer":
                    return MarkLayer;
                case "SlideLayer":
                    return SlideLayer;
                case "Value":
                    return Value;
                default:
                    return null;
            }
        }


    }
}
