//--------------------------------------------------------
// This code is generated by AutoFastGenerator.
// You should not modify the code.
//--------------------------------------------------------

namespace FlowScriptEngineSlimDX.FlowSourceObjects.Matrix
{
    public partial class ValueFlowSourceObject
    {
        public override object GetPropertyValue(string propertyName)
        {
            switch (propertyName)
            {
                case "M11":
                    return M11;
                case "M12":
                    return M12;
                case "M13":
                    return M13;
                case "M14":
                    return M14;
                case "M21":
                    return M21;
                case "M22":
                    return M22;
                case "M23":
                    return M23;
                case "M24":
                    return M24;
                case "M31":
                    return M31;
                case "M32":
                    return M32;
                case "M33":
                    return M33;
                case "M34":
                    return M34;
                case "M41":
                    return M41;
                case "M42":
                    return M42;
                case "M43":
                    return M43;
                case "M44":
                    return M44;
                case "Value":
                    return Value;
                default:
                    return null;
            }
        }

        protected override void SetPropertyValue(string propertyName, object value)
        {
            switch (propertyName)
            {
                case "Value":
                    Value = (SharpDX.Matrix)value;
                    break;
            }
        }

    }
}
