//--------------------------------------------------------
// This code is generated by AutoFastGenerator.
// You should not modify the code.
//--------------------------------------------------------

namespace FlowScriptEngineBasic.FlowSourceObjects.Hashtable
{
    public partial class PairsFlowSourceObject
    {
        public override object GetPropertyValue(string propertyName)
        {
            switch (propertyName)
            {
                case "Pairs":
                    return Pairs;
                default:
                    return null;
            }
        }

        protected override void SetPropertyValue(string propertyName, object value)
        {
            switch (propertyName)
            {
                case "Hashtable":
                    Hashtable = (System.Collections.Generic.Dictionary<System.Object, System.Object>)value;
                    break;
            }
        }

    }
}
