//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowScriptEnginePPDEditor.Properties
{


    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlowScriptEnginePPDEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   説明です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dialog_Setting_Add_Description {
            get {
                return ResourceManager.GetString("Dialog_Setting_Add_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キーです に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dialog_Setting_Add_Key {
            get {
                return ResourceManager.GetString("Dialog_Setting_Add_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最大長です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dialog_Setting_Add_MaxLength {
            get {
                return ResourceManager.GetString("Dialog_Setting_Add_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最大値です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dialog_Setting_Add_MaxValue {
            get {
                return ResourceManager.GetString("Dialog_Setting_Add_MaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最小値です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dialog_Setting_Add_MinValue {
            get {
                return ResourceManager.GetString("Dialog_Setting_Add_MinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象の設定です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dialog_Setting_Add_Setting {
            get {
                return ResourceManager.GetString("Dialog_Setting_Add_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定に項目を追加します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dialog_Setting_Add_Summary {
            get {
                return ResourceManager.GetString("Dialog_Setting_Add_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   値です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dialog_Setting_Add_Value {
            get {
                return ResourceManager.GetString("Dialog_Setting_Add_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択可能な値の一覧です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dialog_Setting_Add_Values {
            get {
                return ResourceManager.GetString("Dialog_Setting_Add_Values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キーです に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dialog_Setting_GetValue_Key {
            get {
                return ResourceManager.GetString("Dialog_Setting_GetValue_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象の設定です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dialog_Setting_GetValue_Setting {
            get {
                return ResourceManager.GetString("Dialog_Setting_GetValue_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定から値を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dialog_Setting_GetValue_Summary {
            get {
                return ResourceManager.GetString("Dialog_Setting_GetValue_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   値です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dialog_Setting_GetValue_Value {
            get {
                return ResourceManager.GetString("Dialog_Setting_GetValue_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定のためのデータセットを初期化します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dialog_Setting_Value_Summary {
            get {
                return ResourceManager.GetString("Dialog_Setting_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定時に表示されるタイトルです に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dialog_Setting_Value_Title {
            get {
                return ResourceManager.GetString("Dialog_Setting_Value_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定のデータセットです に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dialog_Setting_Value_Value {
            get {
                return ResourceManager.GetString("Dialog_Setting_Value_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   結果です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dialog_Show_Result {
            get {
                return ResourceManager.GetString("Dialog_Show_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dialog_Show_Setting {
            get {
                return ResourceManager.GetString("Dialog_Show_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ダイアログを設定に基づき表示します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dialog_Show_Summary {
            get {
                return ResourceManager.GetString("Dialog_Show_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BPMを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Event_Value_BPM {
            get {
                return ResourceManager.GetString("Event_Value_BPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BPMを即時に変更するかどうかを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Event_Value_BPMRapidChange {
            get {
                return ResourceManager.GetString("Event_Value_BPMRapidChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示の仕方を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Event_Value_DisplayState {
            get {
                return ResourceManager.GetString("Event_Value_DisplayState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象のイベントを設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Event_Value_Event {
            get {
                return ResourceManager.GetString("Event_Value_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   初期化順序を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Event_Value_InitializeOrder {
            get {
                return ResourceManager.GetString("Event_Value_InitializeOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   押している間だけサウンドを流すかどうかを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Event_Value_KeepPlayings {
            get {
                return ResourceManager.GetString("Event_Value_KeepPlayings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   動き方を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Event_Value_MoveState {
            get {
                return ResourceManager.GetString("Event_Value_MoveState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ノーツの種類を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Event_Value_NoteType {
            get {
                return ResourceManager.GetString("Event_Value_NoteType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   離したときにサウンドを流すかどうかを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Event_Value_ReleaseSounds {
            get {
                return ResourceManager.GetString("Event_Value_ReleaseSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スライドスケールを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Event_Value_SlideScale {
            get {
                return ResourceManager.GetString("Event_Value_SlideScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   イベントの情報を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Event_Value_Summary {
            get {
                return ResourceManager.GetString("Event_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ボリュームを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Event_Value_VolumePercents {
            get {
                return ResourceManager.GetString("Event_Value_VolumePercents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   イベント一覧を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Event_Values_Summary {
            get {
                return ResourceManager.GetString("Event_Values_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   イベント一覧を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Event_Values_Values {
            get {
                return ResourceManager.GetString("Event_Values_Values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   失敗したときに呼ばれるイベントです に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Execute_Failed {
            get {
                return ResourceManager.GetString("Execute_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実行します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Execute_In {
            get {
                return ResourceManager.GetString("Execute_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   成功したときに呼ばれるイベントです に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Execute_Success {
            get {
                return ResourceManager.GetString("Execute_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レイヤーにマークを追加します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Layer_AddMark_Layer {
            get {
                return ResourceManager.GetString("Layer_AddMark_Layer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マークの位置です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Layer_AddMark_Position {
            get {
                return ResourceManager.GetString("Layer_AddMark_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マークの離す時間です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Layer_AddMark_ReleaseTime {
            get {
                return ResourceManager.GetString("Layer_AddMark_ReleaseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マークの角度です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Layer_AddMark_Rotation {
            get {
                return ResourceManager.GetString("Layer_AddMark_Rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レイヤーにマークを追加します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Layer_AddMark_Summary {
            get {
                return ResourceManager.GetString("Layer_AddMark_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マークの時間です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Layer_AddMark_Time {
            get {
                return ResourceManager.GetString("Layer_AddMark_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マークの種類です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Layer_AddMark_Type {
            get {
                return ResourceManager.GetString("Layer_AddMark_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全てのレイヤーを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Layer_All_All {
            get {
                return ResourceManager.GetString("Layer_All_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全てのレイヤーを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Layer_All_Summary {
            get {
                return ResourceManager.GetString("Layer_All_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択されたレイヤーかどうかを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Layer_Value_IsSelected {
            get {
                return ResourceManager.GetString("Layer_Value_IsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象のレイヤーです に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Layer_Value_Layer {
            get {
                return ResourceManager.GetString("Layer_Value_Layer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マークを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Layer_Value_Marks {
            get {
                return ResourceManager.GetString("Layer_Value_Marks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択されたマークを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Layer_Value_SelectedMark {
            get {
                return ResourceManager.GetString("Layer_Value_SelectedMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択されたマークを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Layer_Value_SelectedMarks {
            get {
                return ResourceManager.GetString("Layer_Value_SelectedMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レイヤーの情報を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Layer_Value_Summary {
            get {
                return ResourceManager.GetString("Layer_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象のマークです に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mark_AssignId_Mark {
            get {
                return ResourceManager.GetString("Mark_AssignId_Mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マークにIDを付与します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mark_AssignId_Summary {
            get {
                return ResourceManager.GetString("Mark_AssignId_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全てのパラメータープリセットです に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mark_ParameterPreset_All_All {
            get {
                return ResourceManager.GetString("Mark_ParameterPreset_All_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全てのパラメータープリセットを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mark_ParameterPreset_All_Summary {
            get {
                return ResourceManager.GetString("Mark_ParameterPreset_All_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プリセットのパラメーター一覧です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mark_ParameterPreset_Value_Parameters {
            get {
                return ResourceManager.GetString("Mark_ParameterPreset_Value_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プリセットの名前です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mark_ParameterPreset_Value_PresetName {
            get {
                return ResourceManager.GetString("Mark_ParameterPreset_Value_PresetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータープリセットの情報を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mark_ParameterPreset_Value_Summary {
            get {
                return ResourceManager.GetString("Mark_ParameterPreset_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象のパラメータープリセットです に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mark_ParameterPreset_Value_Value {
            get {
                return ResourceManager.GetString("Mark_ParameterPreset_Value_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象のファイル名です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mark_PosAndRotation_Load_FileName {
            get {
                return ResourceManager.GetString("Mark_PosAndRotation_Load_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   位置角度の情報を読み取ります に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mark_PosAndRotation_Load_Summary {
            get {
                return ResourceManager.GetString("Mark_PosAndRotation_Load_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   読み取った情報です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mark_PosAndRotation_Load_Values {
            get {
                return ResourceManager.GetString("Mark_PosAndRotation_Load_Values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   位置情報を含むかどうかを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mark_PosAndRotation_Value_HasPosition {
            get {
                return ResourceManager.GetString("Mark_PosAndRotation_Value_HasPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   角度情報を含むかどうかを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mark_PosAndRotation_Value_HasRotation {
            get {
                return ResourceManager.GetString("Mark_PosAndRotation_Value_HasRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   位置を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mark_PosAndRotation_Value_Position {
            get {
                return ResourceManager.GetString("Mark_PosAndRotation_Value_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   角度を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mark_PosAndRotation_Value_Rotation {
            get {
                return ResourceManager.GetString("Mark_PosAndRotation_Value_Rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   位置角度の情報を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mark_PosAndRotation_Value_Summary {
            get {
                return ResourceManager.GetString("Mark_PosAndRotation_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象の位置角度の情報です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mark_PosAndRotation_Value_Value {
            get {
                return ResourceManager.GetString("Mark_PosAndRotation_Value_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象のマークです に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mark_Remove_Mark {
            get {
                return ResourceManager.GetString("Mark_Remove_Mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マークを削除します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mark_Remove_Summary {
            get {
                return ResourceManager.GetString("Mark_Remove_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメーターのキーです に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mark_RemoveParameter_Key {
            get {
                return ResourceManager.GetString("Mark_RemoveParameter_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象のマークです に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mark_RemoveParameter_Mark {
            get {
                return ResourceManager.GetString("Mark_RemoveParameter_Mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マークのパラメーターを削除します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mark_RemoveParameter_Summary {
            get {
                return ResourceManager.GetString("Mark_RemoveParameter_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメーターのキーです に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mark_SetParameter_Key {
            get {
                return ResourceManager.GetString("Mark_SetParameter_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象のマークです に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mark_SetParameter_Mark {
            get {
                return ResourceManager.GetString("Mark_SetParameter_Mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マークにパラメーターを付与します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mark_SetParameter_Summary {
            get {
                return ResourceManager.GetString("Mark_SetParameter_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメーターの値です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mark_SetParameter_Value {
            get {
                return ResourceManager.GetString("Mark_SetParameter_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象のマークです に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mark_SetPosition_Mark {
            get {
                return ResourceManager.GetString("Mark_SetPosition_Mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   位置を設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mark_SetPosition_Position {
            get {
                return ResourceManager.GetString("Mark_SetPosition_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マークの位置を設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mark_SetPosition_Summary {
            get {
                return ResourceManager.GetString("Mark_SetPosition_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象のマークです に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mark_SetRotation_Mark {
            get {
                return ResourceManager.GetString("Mark_SetRotation_Mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   角度を設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mark_SetRotation_Rotation {
            get {
                return ResourceManager.GetString("Mark_SetRotation_Rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マークの角度を設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mark_SetRotation_Summary {
            get {
                return ResourceManager.GetString("Mark_SetRotation_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象のマークです に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mark_SetTime_Mark {
            get {
                return ResourceManager.GetString("Mark_SetTime_Mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マークの時間を設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mark_SetTime_Summary {
            get {
                return ResourceManager.GetString("Mark_SetTime_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   時間です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mark_SetTime_Time {
            get {
                return ResourceManager.GetString("Mark_SetTime_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象のマークです に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mark_SetType_Mark {
            get {
                return ResourceManager.GetString("Mark_SetType_Mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マークのタイプを変更します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mark_SetType_Summary {
            get {
                return ResourceManager.GetString("Mark_SetType_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイプです に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mark_SetType_Type {
            get {
                return ResourceManager.GetString("Mark_SetType_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象のマークです に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mark_UnassignId_Mark {
            get {
                return ResourceManager.GetString("Mark_UnassignId_Mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マークのID割り当てを解除します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mark_UnassignId_Summary {
            get {
                return ResourceManager.GetString("Mark_UnassignId_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IDを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mark_Value_ID {
            get {
                return ResourceManager.GetString("Mark_Value_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   長押しかどうかを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mark_Value_IsLong {
            get {
                return ResourceManager.GetString("Mark_Value_IsLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象のマークを設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mark_Value_Mark {
            get {
                return ResourceManager.GetString("Mark_Value_Mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメーターを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mark_Value_Parameters {
            get {
                return ResourceManager.GetString("Mark_Value_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   位置を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mark_Value_Position {
            get {
                return ResourceManager.GetString("Mark_Value_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リリースの時間を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mark_Value_ReleaseTime {
            get {
                return ResourceManager.GetString("Mark_Value_ReleaseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   角度を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mark_Value_Rotation {
            get {
                return ResourceManager.GetString("Mark_Value_Rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マークの情報を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mark_Value_Summary {
            get {
                return ResourceManager.GetString("Mark_Value_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   時間を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mark_Value_Time {
            get {
                return ResourceManager.GetString("Mark_Value_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイプを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mark_Value_Type {
            get {
                return ResourceManager.GetString("Mark_Value_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示するボタンを設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_Show_Button {
            get {
                return ResourceManager.GetString("MessageBox_Show_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示するキャプションを設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_Show_Caption {
            get {
                return ResourceManager.GetString("MessageBox_Show_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示するアイコンを設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_Show_Icon {
            get {
                return ResourceManager.GetString("MessageBox_Show_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   結果を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_Show_Result {
            get {
                return ResourceManager.GetString("MessageBox_Show_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メッセージボックスを表示します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_Show_Summary {
            get {
                return ResourceManager.GetString("MessageBox_Show_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示するテキストを設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_Show_Text {
            get {
                return ResourceManager.GetString("MessageBox_Show_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   動画の長さを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Movie_Length_Summary {
            get {
                return ResourceManager.GetString("Movie_Length_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   動画の長さを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Movie_Length_Value {
            get {
                return ResourceManager.GetString("Movie_Length_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   動画を一時停止します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Movie_Pause_Summary {
            get {
                return ResourceManager.GetString("Movie_Pause_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   動画を再生します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Movie_Play_Summary {
            get {
                return ResourceManager.GetString("Movie_Play_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   動画の位置を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Movie_Position_Summary {
            get {
                return ResourceManager.GetString("Movie_Position_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   動画の位置を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Movie_Position_Value {
            get {
                return ResourceManager.GetString("Movie_Position_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   動画をシークします に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Movie_Seek_Summary {
            get {
                return ResourceManager.GetString("Movie_Seek_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   シーク位置を設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Movie_Seek_Time {
            get {
                return ResourceManager.GetString("Movie_Seek_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定ファイルライターに反映させるかどうかを設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Movie_SetTrimming_ApplyToIniFileWriter {
            get {
                return ResourceManager.GetString("Movie_SetTrimming_ApplyToIniFileWriter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   下のトリミングを設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Movie_SetTrimming_Bottom {
            get {
                return ResourceManager.GetString("Movie_SetTrimming_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   左のトリミングを設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Movie_SetTrimming_Left {
            get {
                return ResourceManager.GetString("Movie_SetTrimming_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   右のトリミングを設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Movie_SetTrimming_Right {
            get {
                return ResourceManager.GetString("Movie_SetTrimming_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   動画のトリミングを設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Movie_SetTrimming_Summary {
            get {
                return ResourceManager.GetString("Movie_SetTrimming_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   上のトリミングを設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Movie_SetTrimming_Top {
            get {
                return ResourceManager.GetString("Movie_SetTrimming_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   高さを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Movie_Size_Height {
            get {
                return ResourceManager.GetString("Movie_Size_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   動画のサイズを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Movie_Size_Summary {
            get {
                return ResourceManager.GetString("Movie_Size_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   幅を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Movie_Size_Width {
            get {
                return ResourceManager.GetString("Movie_Size_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   動画を停止します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Movie_Stop_Summary {
            get {
                return ResourceManager.GetString("Movie_Stop_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   下のトリミングを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Movie_Trimming_Bottom {
            get {
                return ResourceManager.GetString("Movie_Trimming_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   左のトリミングを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Movie_Trimming_Left {
            get {
                return ResourceManager.GetString("Movie_Trimming_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   右のトリミングを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Movie_Trimming_Right {
            get {
                return ResourceManager.GetString("Movie_Trimming_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   動画のトリミングを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Movie_Trimming_Summary {
            get {
                return ResourceManager.GetString("Movie_Trimming_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   上のトリミングを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Movie_Trimming_Top {
            get {
                return ResourceManager.GetString("Movie_Trimming_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BPMを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Song_Info_BPM {
            get {
                return ResourceManager.GetString("Song_Info_BPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BPM Offsetを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Song_Info_BPMOffset {
            get {
                return ResourceManager.GetString("Song_Info_BPMOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロジェクト名を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Song_Info_ProjectName {
            get {
                return ResourceManager.GetString("Song_Info_ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロジェクトのパスを取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Song_Info_ProjectPath {
            get {
                return ResourceManager.GetString("Song_Info_ProjectPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   譜面の情報を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Song_Info_Summary {
            get {
                return ResourceManager.GetString("Song_Info_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キーです に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Storage_GetValue_Key {
            get {
                return ResourceManager.GetString("Storage_GetValue_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ストレージのキーです に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Storage_GetValue_StorageKey {
            get {
                return ResourceManager.GetString("Storage_GetValue_StorageKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ストレージから値を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Storage_GetValue_Summary {
            get {
                return ResourceManager.GetString("Storage_GetValue_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   値です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Storage_GetValue_Value {
            get {
                return ResourceManager.GetString("Storage_GetValue_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キーです に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Storage_SetValue_Key {
            get {
                return ResourceManager.GetString("Storage_SetValue_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ストレージのキーです に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Storage_SetValue_StorageKey {
            get {
                return ResourceManager.GetString("Storage_SetValue_StorageKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ストレージに値を設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Storage_SetValue_Summary {
            get {
                return ResourceManager.GetString("Storage_SetValue_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   値です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Storage_SetValue_Value {
            get {
                return ResourceManager.GetString("Storage_SetValue_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ターゲットのタイプを調べます に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TemplateIsType_Summary {
            get {
                return ResourceManager.GetString("TemplateIsType_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ターゲットです に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TemplateIsType_Target {
            get {
                return ResourceManager.GetString("TemplateIsType_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ターゲットがタイプであったかどうかです に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TemplateIsType_Value {
            get {
                return ResourceManager.GetString("TemplateIsType_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   値を作成します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TemplateStruct_Summary {
            get {
                return ResourceManager.GetString("TemplateStruct_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   値です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TemplateStruct_Value {
            get {
                return ResourceManager.GetString("TemplateStruct_Value", resourceCulture);
            }
        }
    }
}
