//--------------------------------------------------------
// This code is generated by AutoFastGenerator.
// You should not modify the code.
//--------------------------------------------------------

namespace FlowScriptEnginePPDEditor.FlowSourceObjects.Song
{
    public partial class InfoFlowSourceObject
    {
        public override object GetPropertyValue(string propertyName)
        {
            switch (propertyName)
            {
                case "BPM":
                    return BPM;
                case "BPMOffset":
                    return BPMOffset;
                case "ProjectName":
                    return ProjectName;
                case "ProjectPath":
                    return ProjectPath;
                default:
                    return null;
            }
        }


    }
}
