//--------------------------------------------------------
// This code is generated by AutoFastGenerator.
// You should not modify the code.
//--------------------------------------------------------

namespace FlowScriptEnginePPDEditor.FlowSourceObjects.Layer
{
    public partial class AddLongMarkFlowSourceObject
    {

        protected override void SetPropertyValue(string propertyName, object value)
        {
            switch (propertyName)
            {
                case "Layer":
                    Layer = (PPDEditorCommon.ILayer)value;
                    break;
                case "Position":
                    Position = (SharpDX.Vector2)value;
                    break;
                case "ReleaseTime":
                    ReleaseTime = (System.Single)value;
                    break;
                case "Rotation":
                    Rotation = (System.Single)value;
                    break;
                case "Time":
                    Time = (System.Single)value;
                    break;
                case "Type":
                    Type = (PPDCoreModel.Data.MarkType)value;
                    break;
            }
        }

        public override void ConnectEvent(string eventName, FlowScriptEngine.FlowEventHandler eventHandler)
        {
            switch (eventName)
            {
                case "Failed":
                    Failed += new FlowScriptEngine.FlowEventHandler(eventHandler);
                    break;
                case "Success":
                    Success += new FlowScriptEngine.FlowEventHandler(eventHandler);
                    break;
            }
        }
    }
}
