//--------------------------------------------------------
// This code is generated by AutoFastGenerator.
// You should not modify the code.
//--------------------------------------------------------

namespace FlowScriptEnginePPD.FlowSourceObjects.Song
{
    public partial class InfoFlowSourceObject
    {
        public override object GetPropertyValue(string propertyName)
        {
            switch (propertyName)
            {
                case "AllLongMarkCount":
                    return AllLongMarkCount;
                case "AllMarkCount":
                    return AllMarkCount;
                case "AuthorName":
                    return AuthorName;
                case "BPM":
                    return BPM;
                case "Difficulty":
                    return Difficulty;
                case "DifficultyPointAverage":
                    return DifficultyPointAverage;
                case "DifficultyPointPeak":
                    return DifficultyPointPeak;
                case "DifficultyString":
                    return DifficultyString;
                case "EndTime":
                    return EndTime;
                case "FiveMarkCount":
                    return FiveMarkCount;
                case "FourMarkCount":
                    return FourMarkCount;
                case "IsAuto":
                    return IsAuto;
                case "IsConnect":
                    return IsConnect;
                case "IsDebug":
                    return IsDebug;
                case "IsGodMode":
                    return IsGodMode;
                case "IsMuteSE":
                    return IsMuteSE;
                case "IsRandom":
                    return IsRandom;
                case "IsRegular":
                    return IsRegular;
                case "Marks":
                    return Marks;
                case "NoteType":
                    return NoteType;
                case "OneMarkCount":
                    return OneMarkCount;
                case "SixMarkCount":
                    return SixMarkCount;
                case "SongName":
                    return SongName;
                case "SpeedScale":
                    return SpeedScale;
                case "StartTime":
                    return StartTime;
                case "ThreeMarkCount":
                    return ThreeMarkCount;
                case "TwoMarkCount":
                    return TwoMarkCount;
                default:
                    return null;
            }
        }


    }
}
