//--------------------------------------------------------
// This code is generated by AutoFastGenerator.
// You should not modify the code.
//--------------------------------------------------------

namespace FlowScriptEnginePPD.FlowSourceObjects.Song
{
    public partial class InfoExFlowSourceObject
    {
        public override object GetPropertyValue(string propertyName)
        {
            switch (propertyName)
            {
                case "AllClearCount":
                    return AllClearCount;
                case "AllPlayCount":
                    return AllPlayCount;
                case "BestPerformance":
                    return BestPerformance;
                case "BestPerformanceCoolCount":
                    return BestPerformanceCoolCount;
                case "BestPerformanceGoodCount":
                    return BestPerformanceGoodCount;
                case "BestPerformanceSadCount":
                    return BestPerformanceSadCount;
                case "BestPerformanceSafeCount":
                    return BestPerformanceSafeCount;
                case "BestPerformanceScore":
                    return BestPerformanceScore;
                case "BestPerformanceWorstCount":
                    return BestPerformanceWorstCount;
                case "BestScore":
                    return BestScore;
                case "ClearCount":
                    return ClearCount;
                case "IsAllFirstPlay":
                    return IsAllFirstPlay;
                case "IsFirstPlay":
                    return IsFirstPlay;
                case "PlayCount":
                    return PlayCount;
                case "Results":
                    return Results;
                default:
                    return null;
            }
        }


    }
}
