//--------------------------------------------------------
// This code is generated by AutoFastGenerator.
// You should not modify the code.
//--------------------------------------------------------

namespace FlowScriptEngineBasic.FlowSourceObjects.Enumerable.Lookup
{
    public partial class ValueFlowSourceObject
    {
        public override object GetPropertyValue(string propertyName)
        {
            switch (propertyName)
            {
                case "Count":
                    return Count;
                case "EnumerableWithKey":
                    return EnumerableWithKey;
                default:
                    return null;
            }
        }

        protected override void SetPropertyValue(string propertyName, object value)
        {
            switch (propertyName)
            {
                case "Key":
                    Key = (System.Object)value;
                    break;
                case "Lookup":
                    Lookup = (System.Linq.ILookup<System.Object, System.Object>)value;
                    break;
            }
        }

    }
}
