//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowScriptEngineConsole.Properties
{


    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlowScriptEngineConsole.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   入力メソッドです に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Console_Clear_In {
            get {
                return ResourceManager.GetString("Console_Clear_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コンソールをクリアします に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Console_Clear_Summary {
            get {
                return ResourceManager.GetString("Console_Clear_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力メソッドです に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Console_Read_In {
            get {
                return ResourceManager.GetString("Console_Read_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ２文字以上が入力された場合には次回の呼び出しで２文字目が取得されます に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Console_Read_Remark {
            get {
                return ResourceManager.GetString("Console_Read_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コンソールから一文字取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Console_Read_Summary {
            get {
                return ResourceManager.GetString("Console_Read_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   取得した文字です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Console_Read_Value {
            get {
                return ResourceManager.GetString("Console_Read_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力メソッドです に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Console_ReadLine_In {
            get {
                return ResourceManager.GetString("Console_ReadLine_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バッファーに入力が残っている場合、バッファから優先的に取得されます に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Console_ReadLine_Remark {
            get {
                return ResourceManager.GetString("Console_ReadLine_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コンソールから文字列を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Console_ReadLine_Summary {
            get {
                return ResourceManager.GetString("Console_ReadLine_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   文字列です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Console_ReadLine_Value {
            get {
                return ResourceManager.GetString("Console_ReadLine_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力メソッドです に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Console_Write_In {
            get {
                return ResourceManager.GetString("Console_Write_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コンソールに文字列を出力します。改行は追加されません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Console_Write_Summary {
            get {
                return ResourceManager.GetString("Console_Write_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力する文字列です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Console_Write_Text {
            get {
                return ResourceManager.GetString("Console_Write_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力メソッドです に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Console_WriteLine_In {
            get {
                return ResourceManager.GetString("Console_WriteLine_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コンソールに改行をつけて文字列を出力します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Console_WriteLine_Summary {
            get {
                return ResourceManager.GetString("Console_WriteLine_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力する文字列です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Console_WriteLine_Text {
            get {
                return ResourceManager.GetString("Console_WriteLine_Text", resourceCulture);
            }
        }
    }
}
