//--------------------------------------------------------
// This code is generated by AutoFastGenerator.
// You should not modify the code.
//--------------------------------------------------------

namespace FlowScriptEngineConsole.FlowSourceObjects.Console
{
    public partial class ClearFlowSourceObject
    {


    }
}
