//--------------------------------------------------------
// This code is generated by AutoFastGenerator.
// You should not modify the code.
//--------------------------------------------------------

namespace FlowScriptEngineConsole.FlowSourceObjects.Console
{
    public partial class WriteFlowSourceObject
    {

        protected override void SetPropertyValue(string propertyName, object value)
        {
            switch (propertyName)
            {
                case "Text":
                    Text = (System.String)value;
                    break;
            }
        }

    }
}
