//--------------------------------------------------------
// This code is generated by AutoFastGenerator.
// You should not modify the code.
//--------------------------------------------------------

namespace FlowScriptEngineBasic.FlowSourceObjects.TimeSpan
{
    public partial class CompareFlowSourceObject
    {
        public override object GetPropertyValue(string propertyName)
        {
            switch (propertyName)
            {
                case "Result":
                    return Result;
                default:
                    return null;
            }
        }

        protected override void SetPropertyValue(string propertyName, object value)
        {
            switch (propertyName)
            {
                case "TimeSpan1":
                    TimeSpan1 = (System.TimeSpan)value;
                    break;
                case "TimeSpan2":
                    TimeSpan2 = (System.TimeSpan)value;
                    break;
            }
        }

    }
}
