//--------------------------------------------------------
// This code is generated by AutoFastGenerator.
// You should not modify the code.
//--------------------------------------------------------

namespace FlowScriptEnginePPD.FlowSourceObjects.Graphics.Polygon
{
    public partial class ValueFlowSourceObject
    {
        public override object GetPropertyValue(string propertyName)
        {
            switch (propertyName)
            {
                case "Object":
                    return Object;
                default:
                    return null;
            }
        }

        protected override void SetPropertyValue(string propertyName, object value)
        {
            switch (propertyName)
            {
                case "Path":
                    Path = (System.String)value;
                    break;
                case "PrimitiveCount":
                    PrimitiveCount = (System.Int32)value;
                    break;
                case "PrimitiveType":
                    PrimitiveType = (PPDFramework.PrimitiveType)value;
                    break;
                case "StartIndex":
                    StartIndex = (System.Int32)value;
                    break;
                case "VertexBuffer":
                    VertexBuffer = (PPDFramework.Vertex.VertexInfo)value;
                    break;
                case "VertexCount":
                    VertexCount = (System.Int32)value;
                    break;
            }
        }

        public override void ConnectEvent(string eventName, FlowScriptEngine.FlowEventHandler eventHandler)
        {
            switch (eventName)
            {
                case "Failed":
                    Failed += new FlowScriptEngine.FlowEventHandler(eventHandler);
                    break;
                case "Success":
                    Success += new FlowScriptEngine.FlowEventHandler(eventHandler);
                    break;
            }
        }
    }
}
