//--------------------------------------------------------
// This code is generated by AutoFastGenerator.
// You should not modify the code.
//--------------------------------------------------------

namespace FlowScriptEngineBasic.FlowSourceObjects.DateTime
{
    public partial class CompareFlowSourceObject
    {
        public override object GetPropertyValue(string propertyName)
        {
            switch (propertyName)
            {
                case "Result":
                    return Result;
                default:
                    return null;
            }
        }

        protected override void SetPropertyValue(string propertyName, object value)
        {
            switch (propertyName)
            {
                case "DateTime1":
                    DateTime1 = (System.DateTime)value;
                    break;
                case "DateTime2":
                    DateTime2 = (System.DateTime)value;
                    break;
            }
        }

    }
}
