//--------------------------------------------------------
// This code is generated by AutoFastGenerator.
// You should not modify the code.
//--------------------------------------------------------

namespace FlowScriptEngineBasic.FlowSourceObjects.DateTime
{
    public partial class ValueFlowSourceObject
    {
        public override object GetPropertyValue(string propertyName)
        {
            switch (propertyName)
            {
                case "Date":
                    return Date;
                case "Day":
                    return Day;
                case "DayOfWeek":
                    return DayOfWeek;
                case "DayOfYear":
                    return DayOfYear;
                case "Hour":
                    return Hour;
                case "Millisecond":
                    return Millisecond;
                case "Minute":
                    return Minute;
                case "Month":
                    return Month;
                case "Second":
                    return Second;
                case "TimeOfDay":
                    return TimeOfDay;
                case "Year":
                    return Year;
                default:
                    return null;
            }
        }

        protected override void SetPropertyValue(string propertyName, object value)
        {
            switch (propertyName)
            {
                case "Value":
                    Value = (System.DateTime)value;
                    break;
            }
        }

    }
}
