//--------------------------------------------------------
// This code is generated by AutoFastGenerator.
// You should not modify the code.
//--------------------------------------------------------

namespace FlowScriptEngineBasic.FlowSourceObjects.Math
{
    public partial class DivRemFlowSourceObject
    {
        public override object GetPropertyValue(string propertyName)
        {
            switch (propertyName)
            {
                case "Quotient":
                    return Quotient;
                case "Remainder":
                    return Remainder;
                default:
                    return null;
            }
        }

        protected override void SetPropertyValue(string propertyName, object value)
        {
            switch (propertyName)
            {
                case "A":
                    A = (System.Int32)value;
                    break;
                case "B":
                    B = (System.Int32)value;
                    break;
            }
        }

    }
}
