//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeifenLuo.WinFormsUI.Docking
{


    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WeifenLuo.WinFormsUI.Docking.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Docking に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Category_Docking {
            get {
                return ResourceManager.GetString("Category_Docking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Docking Notification に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Category_DockingNotification {
            get {
                return ResourceManager.GetString("Category_DockingNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Performance に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Category_Performance {
            get {
                return ResourceManager.GetString("Category_Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Property Changed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Category_PropertyChanged {
            get {
                return ResourceManager.GetString("Category_PropertyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (Float) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockAreaEditor_FloatCheckBoxText {
            get {
                return ResourceManager.GetString("DockAreaEditor_FloatCheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Determines if end user drag and drop docking is allowed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockContent_AllowEndUserDocking_Description {
            get {
                return ResourceManager.GetString("DockContent_AllowEndUserDocking_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The size to display the content in auto hide mode. Value &lt; 1 to specify the size in portion; value &gt;= 1 to specify the size in pixel. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockContent_AutoHidePortion_Description {
            get {
                return ResourceManager.GetString("DockContent_AutoHidePortion_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable/Disable the close button of the content. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockContent_CloseButton_Description {
            get {
                return ResourceManager.GetString("DockContent_CloseButton_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shows or hides the close button of the content. This property does not function with System MDI Document Style. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockContent_CloseButtonVisible_Description {
            get {
                return ResourceManager.GetString("DockContent_CloseButtonVisible_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The form must be of type IDockContent. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockContent_Constructor_InvalidForm {
            get {
                return ResourceManager.GetString("DockContent_Constructor_InvalidForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gets or sets a value indicating in which area of the DockPanel the content allowed to show. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockContent_DockAreas_Description {
            get {
                return ResourceManager.GetString("DockContent_DockAreas_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Occurs when the value of DockState property changed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockContent_DockStateChanged_Description {
            get {
                return ResourceManager.GetString("DockContent_DockStateChanged_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Indicates the content will be hidden instead of being closed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockContent_HideOnClose_Description {
            get {
                return ResourceManager.GetString("DockContent_HideOnClose_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The desired docking state when first showing. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockContent_ShowHint_Description {
            get {
                return ResourceManager.GetString("DockContent_ShowHint_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Context menu displayed for the dock pane tab strip. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockContent_TabPageContextMenu_Description {
            get {
                return ResourceManager.GetString("DockContent_TabPageContextMenu_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The tab text displayed in the dock pane. If not set, the Text property will be used. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockContent_TabText_Description {
            get {
                return ResourceManager.GetString("DockContent_TabText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The text displayed when mouse hovers over the tab. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockContent_ToolTipText_Description {
            get {
                return ResourceManager.GetString("DockContent_ToolTipText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The provided value is out of range. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockContentHandler_AutoHidePortion_OutOfRange {
            get {
                return ResourceManager.GetString("DockContentHandler_AutoHidePortion_OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid Value: The value of DockAreas conflicts with current DockState. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockContentHandler_DockAreas_InvalidValue {
            get {
                return ResourceManager.GetString("DockContentHandler_DockAreas_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The pane is invalid. Check the IsFloat and DockPanel properties of this dock pane. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockContentHandler_DockPane_InvalidValue {
            get {
                return ResourceManager.GetString("DockContentHandler_DockPane_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The pane is invalid. Check the IsFloat and DockPanel properties of this dock pane. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockContentHandler_FloatPane_InvalidValue {
            get {
                return ResourceManager.GetString("DockContentHandler_FloatPane_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid value, conflicts with DockableAreas  property. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockContentHandler_IsFloat_InvalidValue {
            get {
                return ResourceManager.GetString("DockContentHandler_IsFloat_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The dock state is invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockContentHandler_SetDockState_InvalidState {
            get {
                return ResourceManager.GetString("DockContentHandler_SetDockState_InvalidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The dock panel is null. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockContentHandler_SetDockState_NullPanel {
            get {
                return ResourceManager.GetString("DockContentHandler_SetDockState_NullPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid beforeContent, it must be contained by the pane. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockContentHandler_Show_InvalidBeforeContent {
            get {
                return ResourceManager.GetString("DockContentHandler_Show_InvalidBeforeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid DockState: Content can not be showed as &quot;Unknown&quot; or &quot;Hidden&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockContentHandler_Show_InvalidDockState {
            get {
                return ResourceManager.GetString("DockContentHandler_Show_InvalidDockState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The previous pane is invalid. It can not be null, and its docking state must not be auto-hide. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockContentHandler_Show_InvalidPrevPane {
            get {
                return ResourceManager.GetString("DockContentHandler_Show_InvalidPrevPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DockPanel can not be null. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockContentHandler_Show_NullDockPanel {
            get {
                return ResourceManager.GetString("DockContentHandler_Show_NullDockPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The Pane can not be null. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockContentHandler_Show_NullPane {
            get {
                return ResourceManager.GetString("DockContentHandler_Show_NullPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid value, check DockableAreas property. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockContentHandler_ShowHint_InvalidValue {
            get {
                return ResourceManager.GetString("DockContentHandler_ShowHint_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Context menu displayed for the dock pane tab strip. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockHandler_TabPageContextMenuStrip_Description {
            get {
                return ResourceManager.GetString("DockHandler_TabPageContextMenuStrip_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Press SHIFT for docking to full side. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockIndicator_ToolTipText {
            get {
                return ResourceManager.GetString("DockIndicator_ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid Content: ActiveContent must be one of the visible contents, or null if there is no visible content. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockPane_ActiveContent_InvalidValue {
            get {
                return ResourceManager.GetString("DockPane_ActiveContent_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid argument: Content can not be &quot;null&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockPane_Constructor_NullContent {
            get {
                return ResourceManager.GetString("DockPane_Constructor_NullContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid argument: The content&apos;s DockPanel can not be &quot;null&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockPane_Constructor_NullDockPanel {
            get {
                return ResourceManager.GetString("DockPane_Constructor_NullDockPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The specified container conflicts with the IsFloat property. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockPane_DockTo_InvalidContainer {
            get {
                return ResourceManager.GetString("DockPane_DockTo_InvalidContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The previous pane does not exist in the nested docking pane collection. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockPane_DockTo_NoPrevPane {
            get {
                return ResourceManager.GetString("DockPane_DockTo_NoPrevPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The container can not be null. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockPane_DockTo_NullContainer {
            get {
                return ResourceManager.GetString("DockPane_DockTo_NullContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The previous pane can not be null when the nested docking pane collection is not empty. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockPane_DockTo_NullPrevPane {
            get {
                return ResourceManager.GetString("DockPane_DockTo_NullPrevPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The previous pane can not be itself. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockPane_DockTo_SelfPrevPane {
            get {
                return ResourceManager.GetString("DockPane_DockTo_SelfPrevPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FloatWindow property can not be set to &quot;null&quot; when DockState is DockState.Float. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockPane_FloatWindow_InvalidValue {
            get {
                return ResourceManager.GetString("DockPane_FloatWindow_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid Content: Content not within the collection. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockPane_SetContentIndex_InvalidContent {
            get {
                return ResourceManager.GetString("DockPane_SetContentIndex_InvalidContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid Index: The index is out of range. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockPane_SetContentIndex_InvalidIndex {
            get {
                return ResourceManager.GetString("DockPane_SetContentIndex_InvalidIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The state for the dock pane is invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockPane_SetDockState_InvalidState {
            get {
                return ResourceManager.GetString("DockPane_SetDockState_InvalidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto Hide に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockPaneCaption_ToolTipAutoHide {
            get {
                return ResourceManager.GetString("DockPaneCaption_ToolTipAutoHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockPaneCaption_ToolTipClose {
            get {
                return ResourceManager.GetString("DockPaneCaption_ToolTipClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Options に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockPaneCaption_ToolTipOptions {
            get {
                return ResourceManager.GetString("DockPaneCaption_ToolTipOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid Content: The content must be auto-hide state and associates with this DockPanel. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockPanel_ActiveAutoHideContent_InvalidValue {
            get {
                return ResourceManager.GetString("DockPanel_ActiveAutoHideContent_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Occurs when the value of the AutoHideWindow&apos;s ActiveContent changed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockPanel_ActiveAutoHideContentChanged_Description {
            get {
                return ResourceManager.GetString("DockPanel_ActiveAutoHideContentChanged_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Occurs when the value of ActiveContentProperty changed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockPanel_ActiveContentChanged_Description {
            get {
                return ResourceManager.GetString("DockPanel_ActiveContentChanged_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Occurs when the value of ActiveDocument property changed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockPanel_ActiveDocumentChanged_Description {
            get {
                return ResourceManager.GetString("DockPanel_ActiveDocumentChanged_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Occurs when the value of ActivePane property changed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockPanel_ActivePaneChanged_Description {
            get {
                return ResourceManager.GetString("DockPanel_ActivePaneChanged_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Determines if the drag and drop docking is allowed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockPanel_AllowEndUserDocking_Description {
            get {
                return ResourceManager.GetString("DockPanel_AllowEndUserDocking_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Determines if the drag and drop nested docking is allowed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockPanel_AllowEndUserNestedDocking_Description {
            get {
                return ResourceManager.GetString("DockPanel_AllowEndUserNestedDocking_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Occurs when a content added to the DockPanel. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockPanel_ContentAdded_Description {
            get {
                return ResourceManager.GetString("DockPanel_ContentAdded_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Occurs when a content removed from the DockPanel. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockPanel_ContentRemoved_Description {
            get {
                return ResourceManager.GetString("DockPanel_ContentRemoved_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The default size of float window. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockPanel_DefaultFloatWindowSize_Description {
            get {
                return ResourceManager.GetString("DockPanel_DefaultFloatWindowSize_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Provides Visual Studio .Net style docking. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockPanel_Description {
            get {
                return ResourceManager.GetString("DockPanel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Size of the bottom docking window. Value &lt; 1 to specify the size in portion; value &gt; 1 to specify the size in pixels. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockPanel_DockBottomPortion_Description {
            get {
                return ResourceManager.GetString("DockPanel_DockBottomPortion_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Size of the left docking window. Value &lt; 1 to specify the size in portion; value &gt; 1 to specify the size in pixels. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockPanel_DockLeftPortion_Description {
            get {
                return ResourceManager.GetString("DockPanel_DockLeftPortion_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The visual skin to use when displaying the docked windows. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockPanel_DockPanelSkin {
            get {
                return ResourceManager.GetString("DockPanel_DockPanelSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The predefined style used as the base for the skin. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockPanel_DockPanelSkinStyle {
            get {
                return ResourceManager.GetString("DockPanel_DockPanelSkinStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Size of the right docking window. Value &lt; 1 to specify the size in portion; value &gt; 1 to specify the size in pixels. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockPanel_DockRightPortion_Description {
            get {
                return ResourceManager.GetString("DockPanel_DockRightPortion_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Size of the top docking window. Value &lt; 1 to specify the size in portion; value &gt; 1 to specify the size in pixels. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockPanel_DockTopPortion_Description {
            get {
                return ResourceManager.GetString("DockPanel_DockTopPortion_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The style of the document window. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockPanel_DocumentStyle_Description {
            get {
                return ResourceManager.GetString("DockPanel_DocumentStyle_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Determines where the tab strip for Document style content is drawn. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockPanel_DocumentTabStripLocation {
            get {
                return ResourceManager.GetString("DockPanel_DocumentTabStripLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The DockPanel has already been initialized. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockPanel_LoadFromXml_AlreadyInitialized {
            get {
                return ResourceManager.GetString("DockPanel_LoadFromXml_AlreadyInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The configuration file&apos;s version is invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockPanel_LoadFromXml_InvalidFormatVersion {
            get {
                return ResourceManager.GetString("DockPanel_LoadFromXml_InvalidFormatVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The XML file format is invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockPanel_LoadFromXml_InvalidXmlFormat {
            get {
                return ResourceManager.GetString("DockPanel_LoadFromXml_InvalidXmlFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid parent form. When using DockingMdi or SystemMdi document style, the DockPanel control must be the child control of the main MDI container form. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockPanel_ParentForm_Invalid {
            get {
                return ResourceManager.GetString("DockPanel_ParentForm_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DockPanel configuration file. Author: Weifen Luo, all rights reserved. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockPanel_Persistor_XmlFileComment1 {
            get {
                return ResourceManager.GetString("DockPanel_Persistor_XmlFileComment1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   !!! AUTOMATICALLY GENERATED FILE. DO NOT MODIFY !!! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockPanel_Persistor_XmlFileComment2 {
            get {
                return ResourceManager.GetString("DockPanel_Persistor_XmlFileComment2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Indicates whether the control layout is right-to-left when the RightToLeft property is set to Yes. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockPanel_RightToLeftLayout_Description {
            get {
                return ResourceManager.GetString("DockPanel_RightToLeftLayout_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid Index: The index is out of range. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockPanel_SetPaneIndex_InvalidIndex {
            get {
                return ResourceManager.GetString("DockPanel_SetPaneIndex_InvalidIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid Pane: DockPane not within the collection. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockPanel_SetPaneIndex_InvalidPane {
            get {
                return ResourceManager.GetString("DockPanel_SetPaneIndex_InvalidPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shows the hidden autohide content when hovering over the tab.  When disabled, the tab must be clicked to show the content. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockPanel_ShowAutoHideContentOnHover_Description {
            get {
                return ResourceManager.GetString("DockPanel_ShowAutoHideContentOnHover_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Determines if the document icon will be displayed in the tab strip. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockPanel_ShowDocumentIcon_Description {
            get {
                return ResourceManager.GetString("DockPanel_ShowDocumentIcon_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Support deeply nested controls.  Disabling this setting may improve resize performance but may cause heavily nested content not to resize. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockPanel_SupportDeeplyNestedContent_Description {
            get {
                return ResourceManager.GetString("DockPanel_SupportDeeplyNestedContent_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockPaneStrip_ToolTipClose {
            get {
                return ResourceManager.GetString("DockPaneStrip_ToolTipClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Window List に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockPaneStrip_ToolTipWindowList {
            get {
                return ResourceManager.GetString("DockPaneStrip_ToolTipWindowList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid argument: DockPanel can not be &quot;null&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FloatWindow_Constructor_NullDockPanel {
            get {
                return ResourceManager.GetString("FloatWindow_Constructor_NullDockPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid Index: The index is out of range. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FloatWindow_SetPaneIndex_InvalidIndex {
            get {
                return ResourceManager.GetString("FloatWindow_SetPaneIndex_InvalidIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid Pane: DockPane not within the collection. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FloatWindow_SetPaneIndex_InvalidPane {
            get {
                return ResourceManager.GetString("FloatWindow_SetPaneIndex_InvalidPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid DockPanel. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDockDragSource_DockTo_InvalidPanel {
            get {
                return ResourceManager.GetString("IDockDragSource_DockTo_InvalidPanel", resourceCulture);
            }
        }
    }
}
