//--------------------------------------------------------
// This code is generated by AutoFastGenerator.
// You should not modify the code.
//--------------------------------------------------------

namespace FlowScriptEnginePPD.FlowSourceObjects.Environment
{
    public partial class ValueFlowSourceObject
    {
        public override object GetPropertyValue(string propertyName)
        {
            switch (propertyName)
            {
                case "AccountId":
                    return AccountId;
                case "DrawSameColorAtSameTimingDisabled":
                    return DrawSameColorAtSameTimingDisabled;
                case "FontSize":
                    return FontSize;
                case "FPS":
                    return FPS;
                case "IsLogined":
                    return IsLogined;
                case "LastDrawTime":
                    return LastDrawTime;
                case "LastUpdateTime":
                    return LastUpdateTime;
                case "MonitorLatency":
                    return MonitorLatency;
                case "MovieLatency":
                    return MovieLatency;
                case "UserName":
                    return UserName;
                case "WindowHeight":
                    return WindowHeight;
                case "WindowWidth":
                    return WindowWidth;
                default:
                    return null;
            }
        }


    }
}
