//--------------------------------------------------------
// This code is generated by AutoFastGenerator.
// You should not modify the code.
//--------------------------------------------------------

namespace FlowScriptEnginePPD.FlowSourceObjects.GameResult
{
    public partial class ValueFlowSourceObject
    {
        public override object GetPropertyValue(string propertyName)
        {
            switch (propertyName)
            {
                case "CoolCount":
                    return CoolCount;
                case "CurrentCombo":
                    return CurrentCombo;
                case "CurrentLife":
                    return CurrentLife;
                case "CurrentScore":
                    return CurrentScore;
                case "ExpectedTotalSlideBonus":
                    return ExpectedTotalSlideBonus;
                case "GoodCount":
                    return GoodCount;
                case "HoldBonus":
                    return HoldBonus;
                case "IsReplaying":
                    return IsReplaying;
                case "IsRetrying":
                    return IsRetrying;
                case "MaxCombo":
                    return MaxCombo;
                case "MaxLife":
                    return MaxLife;
                case "MinLife":
                    return MinLife;
                case "SadCount":
                    return SadCount;
                case "SafeCount":
                    return SafeCount;
                case "SlideBonus":
                    return SlideBonus;
                case "WorstCount":
                    return WorstCount;
                default:
                    return null;
            }
        }


        public override void ConnectEvent(string eventName, FlowScriptEngine.FlowEventHandler eventHandler)
        {
            switch (eventName)
            {
                case "Died":
                    Died += new FlowScriptEngine.FlowEventHandler(eventHandler);
                    break;
            }
        }
    }
}
