//--------------------------------------------------------
// This code is generated by AutoFastGenerator.
// You should not modify the code.
//--------------------------------------------------------

namespace FlowScriptEngineBasic.FlowSourceObjects.Array
{
    public partial class BinarySearchWithLimitFlowSourceObject
    {
        public override object GetPropertyValue(string propertyName)
        {
            switch (propertyName)
            {
                case "FoundIndex":
                    return FoundIndex;
                case "X":
                    return X;
                case "Y":
                    return Y;
                default:
                    return null;
            }
        }

        protected override void SetPropertyValue(string propertyName, object value)
        {
            switch (propertyName)
            {
                case "Array":
                    Array = (System.Object[])value;
                    break;
                case "Length":
                    Length = (System.Int32)value;
                    break;
                case "Result":
                    Result = (System.Int32)value;
                    break;
                case "StartIndex":
                    StartIndex = (System.Int32)value;
                    break;
                case "Value":
                    Value = (System.Object)value;
                    break;
            }
        }

        public override void ConnectEvent(string eventName, FlowScriptEngine.FlowEventHandler eventHandler)
        {
            switch (eventName)
            {
                case "Compare":
                    Compare += new FlowScriptEngine.FlowEventHandler(eventHandler);
                    break;
                case "Failed":
                    Failed += new FlowScriptEngine.FlowEventHandler(eventHandler);
                    break;
                case "Success":
                    Success += new FlowScriptEngine.FlowEventHandler(eventHandler);
                    break;
            }
        }
    }
}
