//--------------------------------------------------------
// This code is generated by AutoFastGenerator.
// You should not modify the code.
//--------------------------------------------------------

namespace FlowScriptEngineBasic.FlowSourceObjects.Array
{
    public partial class FromElementFlowSourceObject
    {
        public override object GetPropertyValue(string propertyName)
        {
            switch (propertyName)
            {
                case "Value":
                    return Value;
                default:
                    return null;
            }
        }

        protected override void SetPropertyValue(string propertyName, object value)
        {
            switch (propertyName)
            {
                case "A":
                    A = (System.Object)value;
                    break;
                case "B":
                    B = (System.Object)value;
                    break;
                case "C":
                    C = (System.Object)value;
                    break;
                case "D":
                    D = (System.Object)value;
                    break;
                case "E":
                    E = (System.Object)value;
                    break;
                case "F":
                    F = (System.Object)value;
                    break;
                case "IsExpanded":
                    IsExpanded = (System.Boolean)value;
                    break;
            }
        }

    }
}
