//--------------------------------------------------------
// This code is generated by AutoFastGenerator.
// You should not modify the code.
//--------------------------------------------------------

namespace FlowScriptEngineBasic.FlowSourceObjects.Logic
{
    public partial class IfFlowSourceObject
    {

        protected override void SetPropertyValue(string propertyName, object value)
        {
            switch (propertyName)
            {
                case "Condition":
                    Condition = (System.Boolean)value;
                    break;
            }
        }

        public override void ConnectEvent(string eventName, FlowScriptEngine.FlowEventHandler eventHandler)
        {
            switch (eventName)
            {
                case "OnFalse":
                    OnFalse += new FlowScriptEngine.FlowEventHandler(eventHandler);
                    break;
                case "OnTrue":
                    OnTrue += new FlowScriptEngine.FlowEventHandler(eventHandler);
                    break;
            }
        }
    }
}
