//--------------------------------------------------------
// This code is generated by AutoFastGenerator.
// You should not modify the code.
//--------------------------------------------------------

namespace FlowScriptEngineBasic.FlowSourceObjects.Logic
{
    public partial class SwitchFlowSourceObject
    {

        protected override void SetPropertyValue(string propertyName, object value)
        {
            switch (propertyName)
            {
                case "Target1":
                    Target1 = (System.Object)value;
                    break;
                case "Target2":
                    Target2 = (System.Object)value;
                    break;
                case "Target3":
                    Target3 = (System.Object)value;
                    break;
                case "Target4":
                    Target4 = (System.Object)value;
                    break;
                case "Target5":
                    Target5 = (System.Object)value;
                    break;
                case "Target6":
                    Target6 = (System.Object)value;
                    break;
                case "Value":
                    Value = (System.Object)value;
                    break;
            }
        }

        public override void ConnectEvent(string eventName, FlowScriptEngine.FlowEventHandler eventHandler)
        {
            switch (eventName)
            {
                case "Default":
                    Default += new FlowScriptEngine.FlowEventHandler(eventHandler);
                    break;
                case "Out1":
                    Out1 += new FlowScriptEngine.FlowEventHandler(eventHandler);
                    break;
                case "Out2":
                    Out2 += new FlowScriptEngine.FlowEventHandler(eventHandler);
                    break;
                case "Out3":
                    Out3 += new FlowScriptEngine.FlowEventHandler(eventHandler);
                    break;
                case "Out4":
                    Out4 += new FlowScriptEngine.FlowEventHandler(eventHandler);
                    break;
                case "Out5":
                    Out5 += new FlowScriptEngine.FlowEventHandler(eventHandler);
                    break;
                case "Out6":
                    Out6 += new FlowScriptEngine.FlowEventHandler(eventHandler);
                    break;
            }
        }
    }
}
