//--------------------------------------------------------
// This code is generated by AutoFastGenerator.
// You should not modify the code.
//--------------------------------------------------------

namespace FlowScriptEnginePPD.FlowSourceObjects
{
    public partial class BPMFlowSourceObject
    {
        public override object GetPropertyValue(string propertyName)
        {
            switch (propertyName)
            {
                case "CurrentBPM":
                    return CurrentBPM;
                case "TargetBPM":
                    return TargetBPM;
                default:
                    return null;
            }
        }

        protected override void SetPropertyValue(string propertyName, object value)
        {
            switch (propertyName)
            {
                case "CurrentBPM":
                    CurrentBPM = (System.Single)value;
                    break;
                case "TargetBPM":
                    TargetBPM = (System.Single)value;
                    break;
            }
        }

    }
}
