//--------------------------------------------------------
// This code is generated by AutoFastGenerator.
// You should not modify the code.
//--------------------------------------------------------

namespace FlowScriptEnginePPD.FlowSourceObjects
{
    public partial class HoldFlowSourceObject
    {
        public override object GetPropertyValue(string propertyName)
        {
            switch (propertyName)
            {
                case "CurrentHoldScore":
                    return CurrentHoldScore;
                case "HoldMarks":
                    return HoldMarks;
                case "MaxHoldBonus":
                    return MaxHoldBonus;
                default:
                    return null;
            }
        }


        public override void ConnectEvent(string eventName, FlowScriptEngine.FlowEventHandler eventHandler)
        {
            switch (eventName)
            {
                case "Change":
                    Change += new FlowScriptEngine.FlowEventHandler(eventHandler);
                    break;
                case "End":
                    End += new FlowScriptEngine.FlowEventHandler(eventHandler);
                    break;
                case "MaxHold":
                    MaxHold += new FlowScriptEngine.FlowEventHandler(eventHandler);
                    break;
                case "Start":
                    Start += new FlowScriptEngine.FlowEventHandler(eventHandler);
                    break;
            }
        }
    }
}
