//--------------------------------------------------------
// This code is generated by AutoFastGenerator.
// You should not modify the code.
//--------------------------------------------------------

namespace FlowScriptEngineBasic.FlowSourceObjects.String
{
    public partial class SplitFlowSourceObject
    {
        public override object GetPropertyValue(string propertyName)
        {
            switch (propertyName)
            {
                case "Value":
                    return Value;
                default:
                    return null;
            }
        }

        protected override void SetPropertyValue(string propertyName, object value)
        {
            switch (propertyName)
            {
                case "A":
                    A = (System.String)value;
                    break;
                case "RemoveEmpty":
                    RemoveEmpty = (System.Boolean)value;
                    break;
                case "Separators":
                    Separators = (System.Collections.Generic.IEnumerable<System.Object>)value;
                    break;
            }
        }

    }
}
