//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowScriptEngineBasicExtension.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlowScriptEngineBasicExtension.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   終了インデックスを設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Enumerable_Range_EndIndex {
            get {
                return ResourceManager.GetString("Enumerable_Range_EndIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   数値の列挙を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Enumerable_Range_Range {
            get {
                return ResourceManager.GetString("Enumerable_Range_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開始インデックスを設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Enumerable_Range_StartIndex {
            get {
                return ResourceManager.GetString("Enumerable_Range_StartIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ステップを設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Enumerable_Range_Step {
            get {
                return ResourceManager.GetString("Enumerable_Range_Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開始インデックスから終了インデックスを除くまでの数値の列挙を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Enumerable_Range_Summary {
            get {
                return ResourceManager.GetString("Enumerable_Range_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デフォルト値を設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Hashtable_ParseValue_Default {
            get {
                return ResourceManager.GetString("Hashtable_ParseValue_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象のハッシュテーブルを設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Hashtable_ParseValue_Hashtable {
            get {
                return ResourceManager.GetString("Hashtable_ParseValue_Hashtable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キーを設定します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Hashtable_ParseValue_Key {
            get {
                return ResourceManager.GetString("Hashtable_ParseValue_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パースに失敗したときのイベントです に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Hashtable_ParseValue_ParseFailed {
            get {
                return ResourceManager.GetString("Hashtable_ParseValue_ParseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   値をパースして取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Hashtable_ParseValue_Summary {
            get {
                return ResourceManager.GetString("Hashtable_ParseValue_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   値を取得します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Hashtable_ParseValue_Value {
            get {
                return ResourceManager.GetString("Hashtable_ParseValue_Value", resourceCulture);
            }
        }
    }
}
