//--------------------------------------------------------
// This code is generated by AutoFastGenerator.
// You should not modify the code.
//--------------------------------------------------------

namespace FlowScriptEnginePPD.FlowSourceObjects.Mark
{
    public partial class DynamicCreateFlowSourceObject
    {

        protected override void SetPropertyValue(string propertyName, object value)
        {
            switch (propertyName)
            {
                case "Angle":
                    Angle = (System.Single)value;
                    break;
                case "EndTime":
                    EndTime = (System.Single)value;
                    break;
                case "IsLong":
                    IsLong = (System.Boolean)value;
                    break;
                case "MarkID":
                    MarkID = (System.Int32)value;
                    break;
                case "MarkType":
                    MarkType = (PPDCoreModel.Data.MarkType)value;
                    break;
                case "Position":
                    Position = (SharpDX.Vector2)value;
                    break;
                case "Time":
                    Time = (System.Single)value;
                    break;
            }
        }

        public override void ConnectEvent(string eventName, FlowScriptEngine.FlowEventHandler eventHandler)
        {
            switch (eventName)
            {
                case "Failed":
                    Failed += new FlowScriptEngine.FlowEventHandler(eventHandler);
                    break;
                case "Success":
                    Success += new FlowScriptEngine.FlowEventHandler(eventHandler);
                    break;
            }
        }
    }
}
