//--------------------------------------------------------
// This code is generated by AutoFastGenerator.
// You should not modify the code.
//--------------------------------------------------------

namespace FlowScriptEnginePPD.FlowSourceObjects.Mark
{
    public partial class ProcessEvaluateAnyFlowSourceObject
    {
        public override object GetPropertyValue(string propertyName)
        {
            switch (propertyName)
            {
                case "EffectType":
                    return EffectType;
                case "HasSameTimingMark":
                    return HasSameTimingMark;
                case "IsAC":
                    return IsAC;
                case "IsACFT":
                    return IsACFT;
                case "IsLong":
                    return IsLong;
                case "IsMissPress":
                    return IsMissPress;
                case "IsRelease":
                    return IsRelease;
                case "IsRight":
                    return IsRight;
                case "IsScratch":
                    return IsScratch;
                case "MarkID":
                    return MarkID;
                case "Parameters":
                    return Parameters;
                case "Position":
                    return Position;
                case "ReleaseTime":
                    return ReleaseTime;
                case "Rotation":
                    return Rotation;
                case "SameTimingMarks":
                    return SameTimingMarks;
                case "SlideScale":
                    return SlideScale;
                case "Time":
                    return Time;
                case "Type":
                    return Type;
                default:
                    return null;
            }
        }

        protected override void SetPropertyValue(string propertyName, object value)
        {
            switch (propertyName)
            {
                case "EvaluateRequired":
                    EvaluateRequired = (System.Boolean)value;
                    break;
                case "Handled":
                    Handled = (System.Boolean)value;
                    break;
            }
        }

        public override void ConnectEvent(string eventName, FlowScriptEngine.FlowEventHandler eventHandler)
        {
            switch (eventName)
            {
                case "Out":
                    Out += new FlowScriptEngine.FlowEventHandler(eventHandler);
                    break;
            }
        }
    }
}
