//--------------------------------------------------------
// This code is generated by AutoFastGenerator.
// You should not modify the code.
//--------------------------------------------------------

namespace FlowScriptEngineBasic.FlowSourceObjects.Enumerable.Ordered
{
    public partial class ThenByFlowSourceObject
    {
        public override object GetPropertyValue(string propertyName)
        {
            switch (propertyName)
            {
                case "OrderedEnumerable":
                    return OrderedEnumerable;
                case "Value":
                    return Value;
                case "X":
                    return X;
                case "Y":
                    return Y;
                default:
                    return null;
            }
        }

        protected override void SetPropertyValue(string propertyName, object value)
        {
            switch (propertyName)
            {
                case "CompareResult":
                    CompareResult = (System.Int32)value;
                    break;
                case "OrderedEnumerable":
                    OrderedEnumerable = (System.Linq.IOrderedEnumerable<System.Object>)value;
                    break;
                case "SelectResult":
                    SelectResult = (System.Object)value;
                    break;
            }
        }

        public override void ConnectEvent(string eventName, FlowScriptEngine.FlowEventHandler eventHandler)
        {
            switch (eventName)
            {
                case "Compare":
                    Compare += new FlowScriptEngine.FlowEventHandler(eventHandler);
                    break;
                case "Select":
                    Select += new FlowScriptEngine.FlowEventHandler(eventHandler);
                    break;
            }
        }
    }
}
