//--------------------------------------------------------
// This code is generated by AutoFastGenerator.
// You should not modify the code.
//--------------------------------------------------------

namespace FlowScriptEngineBasic.FlowSourceObjects.Enumerable
{
    public partial class GroupJoinFlowSourceObject
    {
        public override object GetPropertyValue(string propertyName)
        {
            switch (propertyName)
            {
                case "Enumerable":
                    return Enumerable;
                case "InnerSelectValue":
                    return InnerSelectValue;
                case "OuterSelectValue":
                    return OuterSelectValue;
                case "ResultSelectValue":
                    return ResultSelectValue;
                case "ResultSelectValues":
                    return ResultSelectValues;
                default:
                    return null;
            }
        }

        protected override void SetPropertyValue(string propertyName, object value)
        {
            switch (propertyName)
            {
                case "Enumerable":
                    Enumerable = (System.Collections.Generic.IEnumerable<System.Object>)value;
                    break;
                case "InnerEnumerable":
                    InnerEnumerable = (System.Collections.Generic.IEnumerable<System.Object>)value;
                    break;
                case "InnerSelectResult":
                    InnerSelectResult = (System.Object)value;
                    break;
                case "OuterSelectResult":
                    OuterSelectResult = (System.Object)value;
                    break;
                case "ResultSelectResult":
                    ResultSelectResult = (System.Object)value;
                    break;
            }
        }

        public override void ConnectEvent(string eventName, FlowScriptEngine.FlowEventHandler eventHandler)
        {
            switch (eventName)
            {
                case "InnerSelect":
                    InnerSelect += new FlowScriptEngine.FlowEventHandler(eventHandler);
                    break;
                case "OuterSelect":
                    OuterSelect += new FlowScriptEngine.FlowEventHandler(eventHandler);
                    break;
                case "ResultSelect":
                    ResultSelect += new FlowScriptEngine.FlowEventHandler(eventHandler);
                    break;
            }
        }
    }
}
