//--------------------------------------------------------
// This code is generated by AutoFastGenerator.
// You should not modify the code.
//--------------------------------------------------------

namespace FlowScriptEngineBasic.FlowSourceObjects.Enumerable
{
    public partial class SequentialEqualFlowSourceObject
    {
        public override object GetPropertyValue(string propertyName)
        {
            switch (propertyName)
            {
                case "Value":
                    return Value;
                default:
                    return null;
            }
        }

        protected override void SetPropertyValue(string propertyName, object value)
        {
            switch (propertyName)
            {
                case "First":
                    First = (System.Collections.Generic.IEnumerable<System.Object>)value;
                    break;
                case "Second":
                    Second = (System.Collections.Generic.IEnumerable<System.Object>)value;
                    break;
            }
        }

    }
}
