//--------------------------------------------------------
// This code is generated by AutoFastGenerator.
// You should not modify the code.
//--------------------------------------------------------

namespace FlowScriptEnginePPD.FlowSourceObjects.Mod
{
    public partial class EntryPointFlowSourceObject
    {


        public override void ConnectEvent(string eventName, FlowScriptEngine.FlowEventHandler eventHandler)
        {
            switch (eventName)
            {
                case "Start":
                    Start += new FlowScriptEngine.FlowEventHandler(eventHandler);
                    break;
            }
        }
    }
}
