//--------------------------------------------------------
// This code is generated by AutoFastGenerator.
// You should not modify the code.
//--------------------------------------------------------

namespace FlowScriptEngineBasicExtension.FlowSourceObjects.Hashtable
{
    public partial class ParseFloatValueFlowSourceObject
    {
        public override object GetPropertyValue(string propertyName)
        {
            switch (propertyName)
            {
                case "Value":
                    return Value;
                default:
                    return null;
            }
        }

        protected override void SetPropertyValue(string propertyName, object value)
        {
            switch (propertyName)
            {
                case "Default":
                    Default = (System.Single)value;
                    break;
                case "Hashtable":
                    Hashtable = (System.Collections.Generic.Dictionary<System.Object, System.Object>)value;
                    break;
                case "Key":
                    Key = (System.String)value;
                    break;
            }
        }

        public override void ConnectEvent(string eventName, FlowScriptEngine.FlowEventHandler eventHandler)
        {
            switch (eventName)
            {
                case "ParseFailed":
                    ParseFailed += new FlowScriptEngine.FlowEventHandler(eventHandler);
                    break;
            }
        }
    }
}
