//--------------------------------------------------------
// This code is generated by AutoFastGenerator.
// You should not modify the code.
//--------------------------------------------------------

namespace FlowScriptEnginePPDEditor.FlowSourceObjects.Movie
{
    public partial class SetTrimmingFlowSourceObject
    {

        protected override void SetPropertyValue(string propertyName, object value)
        {
            switch (propertyName)
            {
                case "ApplyToIniFileWriter":
                    ApplyToIniFileWriter = (System.Boolean)value;
                    break;
                case "Bottom":
                    Bottom = (System.Single)value;
                    break;
                case "Left":
                    Left = (System.Single)value;
                    break;
                case "Right":
                    Right = (System.Single)value;
                    break;
                case "Top":
                    Top = (System.Single)value;
                    break;
            }
        }

        public override void ConnectEvent(string eventName, FlowScriptEngine.FlowEventHandler eventHandler)
        {
            switch (eventName)
            {
                case "Failed":
                    Failed += new FlowScriptEngine.FlowEventHandler(eventHandler);
                    break;
                case "Success":
                    Success += new FlowScriptEngine.FlowEventHandler(eventHandler);
                    break;
            }
        }
    }
}
