//--------------------------------------------------------
// This code is generated by AutoFastGenerator.
// You should not modify the code.
//--------------------------------------------------------

namespace FlowScriptEnginePPDEditor.FlowSourceObjects.Movie
{
    public partial class TrimmingFlowSourceObject
    {
        public override object GetPropertyValue(string propertyName)
        {
            switch (propertyName)
            {
                case "Bottom":
                    return Bottom;
                case "Left":
                    return Left;
                case "Right":
                    return Right;
                case "Top":
                    return Top;
                default:
                    return null;
            }
        }


    }
}
