//--------------------------------------------------------
// This code is generated by AutoFastGenerator.
// You should not modify the code.
//--------------------------------------------------------

namespace FlowScriptEngineBasic.FlowSourceObjects.ContextScope
{
    public partial class InvokeEventFlowSourceObject
    {

        protected override void SetPropertyValue(string propertyName, object value)
        {
            switch (propertyName)
            {
                case "Arg":
                    Arg = (System.Object)value;
                    break;
                case "EventName":
                    EventName = (System.String)value;
                    break;
            }
        }

    }
}
