//--------------------------------------------------------
// This code is generated by AutoFastGenerator.
// You should not modify the code.
//--------------------------------------------------------

namespace FlowScriptEngineBasic.FlowSourceObjects.ContextScope
{
    public partial class SetValueFlowSourceObject
    {

        protected override void SetPropertyValue(string propertyName, object value)
        {
            switch (propertyName)
            {
                case "Value":
                    Value = (System.Object)value;
                    break;
                case "ValueName":
                    ValueName = (System.String)value;
                    break;
            }
        }

    }
}
