//--------------------------------------------------------
// This code is generated by AutoFastGenerator.
// You should not modify the code.
//--------------------------------------------------------

namespace FlowScriptEnginePPDEditor.FlowSourceObjects.Mark.PosAndRotation
{
    public partial class ValueFlowSourceObject
    {
        public override object GetPropertyValue(string propertyName)
        {
            switch (propertyName)
            {
                case "HasPosition":
                    return HasPosition;
                case "HasRotation":
                    return HasRotation;
                case "Position":
                    return Position;
                case "Rotation":
                    return Rotation;
                default:
                    return null;
            }
        }

        protected override void SetPropertyValue(string propertyName, object value)
        {
            switch (propertyName)
            {
                case "Value":
                    Value = (PPDEditorCommon.IPosAndAngle)value;
                    break;
            }
        }

    }
}
