//--------------------------------------------------------
// This code is generated by AutoFastGenerator.
// You should not modify the code.
//--------------------------------------------------------

namespace FlowScriptEnginePPDEditor.FlowSourceObjects.Mark
{
    public partial class ValueFlowSourceObject
    {
        public override object GetPropertyValue(string propertyName)
        {
            switch (propertyName)
            {
                case "ID":
                    return ID;
                case "IsLong":
                    return IsLong;
                case "Parameters":
                    return Parameters;
                case "Position":
                    return Position;
                case "ReleaseTime":
                    return ReleaseTime;
                case "Rotation":
                    return Rotation;
                case "Time":
                    return Time;
                case "Type":
                    return Type;
                default:
                    return null;
            }
        }

        protected override void SetPropertyValue(string propertyName, object value)
        {
            switch (propertyName)
            {
                case "Mark":
                    Mark = (PPDEditorCommon.IEditorMarkInfo)value;
                    break;
            }
        }

    }
}
